# 现代科研 {#know}

现代科研对于任何研究人员而言都是一个庞杂的知识体系，个体科研人员终其一生也只能在一个或几个方向上做些许的探索，所有人都是带着有限的知识背景进入到科研中去验证或发现新知。因此，面对不懂的知识或日新月异的技术发展时不必惊慌焦虑，这是正常现象。很多问题目前还没有或几乎不可能有完美答案，很多技术也还没找到最好的应用场景。不过，在直面这些问题与趋势前，我们要了解理清自己的知识框架，然后打造自己的知识体系，伴随经验与灵感去拓展自己与学术界的知识边疆，当然从一开始就要认识并接受到人本身存在的局限性，特别是认知偏误。

## 科学知识的五个层次

科研的基础是前人传下来的知识，知识大体可分为经验与规律。前者带有一定个人色彩，经常没有经过严谨的验证，还有些经验知识只能算个人观点，当然这不妨碍知识的应用。规律则具备客观性，经过了大量验证且有较为严格的证明与论证过程，也都具备应用场景限制。教育能传承的科学知识大都属于规律，而科研则可看作从经验中提取普遍规律的过程。但知识本身也有不同层次，了解这些层次是为了同不同知识层次交流时能减少隔阂与无效沟通，一个简单的原则就是尽可能与知识层次高的人沟通，不过也要清楚这对于知识层次高的人而言很多时候属于浪费时间。

### 背景组

现代社会中中等教育已经基本实现普及，因此完成义务教育可以代表大多数人的知识背景。这里要意识到九年义务教育之后，进入普通高中还是职业学校会产生第一次分工，对于高中到大学一路走下来的人可能意识不到同龄人中大概三分之一已经走了职高高职这条更注重技术经验累积的职业路线。需要注意的是国内初中毕业生比例在2020年的人口中大概是占到六成，依然存在大量人口可能不具备基本的义务教育阶段的科学知识，因此面向全社会的知识交流难度要定在九年义务教育水平。而这部分知识一般侧重原理或事实本身，或者说学到的是通识，例如地球是圆的、力学有三大定律、元素周期表是按什么排的…这类知识其实就算老师不教，百科类网站也能很容易找到。这一阶段的知识分科包括但不限于语数外理化生史地政音体美，就是中小学课程表上那些学科，没有这些基本知识，现代社会陌生人间交流都成问题。

### 已知的已知组

大学毕业水平。主要指专业知识，例如 PM2.5 是怎么回事？行星间距离如何测量？端粒长度跟寿命关系等。这个是社会大多数人科学背景知识的上限，也是职业化的下限。如果继续深究，基本就是做这一行的职业人士才了解，需要经验积累。传统职业学科包括医学、会计、法律、工程学、建筑、计算机科学、金融、护理、工商管理等，这类学科拿到学士学位就表明你已经掌握了这部分内容，可以成为社会螺丝钉了，最多需要学到硕士，从事研究的比较少也不太需要。

目前这个层次的科学知识几乎可以被互联网导论级公开课覆盖，职业知识一般有自己的学科框架跟体系。但学科间壁垒明显，如果相关知识是构建在高度结构化的知识框架上，那么很有可能被机器识别。也就是说，死记硬背的知识是最容易被替代的，掌握这些知识是基础但更重要的是如何使用及经验累积。

### 已知的未知组

这部分的知识是从已知走向未知，知识都是比较前沿的探索性尝试，很可能被后续结果推翻掉。但就研究思想层次看，其实即使一线科研工作者自己可能都比较迷糊，大部分人是站在前人基础上往前推进。前人的研究结论容易保存，但思想可能早就消散了，过个十几年重新发明发现一遍规律的情况并不鲜见。这阶段的知识因为开始走向应用所以学科间开始互通，边缘性综合性研究方向会出现。科研人员的知识水平基本是这个层次的，知道前沿在哪里但还在探索。统计学也是这个阶段常用手段，但需要使用者理解方法本质，人工智能可作为研究方法但无法职业替代，因为探索性的思路还得人来启发。

当前职业化的学术研究的问题大都处于已知的未知，例如纳米材料、表观遗传学、基因修饰技术、测序技术、蛋白质结晶、组学、量子计算机、区块链、深度学习、虚拟现实、增强现实、干细胞、气候变化、3D 打印、生物入侵、物联网、可穿戴设备、无人驾驶等，这些学科里科学问题是比较清晰的，更多借助技术进步特别是分析技术的进步来回答问题。这部分知识的介绍一般不算做科普而更多是学科内交流，内容会出现在高等教育专业课及研究生教育的文献讨论班之中，当然大众媒体也会从事实角度进行报道但不会涉及细节。

### 未知的已知组

这个层次侧重于整合已有知识进行创新得到的新知识，基本上只有经验很丰富的人才能站到一定高度上理解一个学科。此时谈思想谈逻辑之外要整合学科历史，把发展沿革搞清楚。将学科间知识高度互通是少数有洞见的科研人员才能做到的事，统计学或人工智能在这个层次知识已然失灵，只能摸着石头过河。整合知识的能力跟分析知识点能力所需要的知识量是不在一个数量级的，现在很多有重大意义的新发现实际就是综合了不同领域知识的结果而不是凭空出现的，这即需要有专精知识的人，也需要有人能把这些知识整合起来，想获得这类知识多需要团队协作。我们可以把这个学科统称为复杂性科学或系统科学。

现代社会的分工促进效率原则在这里是失灵的，很多这个层次的科学问题需要的是多视角证明或者需要别的学科的技术工具来帮忙。然而，现代科研教育体系只能保证到已知的未知组层次人才的培养，在未知的已知层次需要的更多是科研项目经验与多学科研究思路的累积，很难通过课堂来教授。这里虽然研究的是科学问题，但采用的实际是工程手段，通过整合或者接纳其他学科的研究手段与方法去回答复杂的现实问题，此时问题是中心，学科是手段。

### 未知的未知组

这个组就是人类知识天花板了，或者走向科幻领域了。不过哪怕是科幻也是科研人员要读的，因为你可以体会其中思考的乐趣，当然知识背景设定就不要细看了。这个组需要你能构建出一个逻辑自洽且符合现实的知识理论体系，其实就是形而上的东西了，但小说中是可以虚构出来的并展示不同其实当前并不存在的可能性。

总结下就是职业化的现代科研知识集中在探索各自学科已知的未知内容不过也在逐渐转到未知的已知这类面向问题的工程化科研的阶段。至于未知的未知，大概只能从人的虚构能力里发现些端倪吧。

## 知识体系的时间构建

除了基于已知未知这种简单的面向科研既有知识的划分方法，个人知识还需要一个时间与逻辑上的累积与构建，这样可以自洽于其他非科研知识，毕竟科研是有噪音边界的，但更广义的知识却不一定有噪音来指出不确定性。

《四库全书》采用了经史子集的划分方法，内在逻辑是把经典的普世规律、过往的经验事实、学科专业知识与个人文集或观点进行了区分。这种分法从可靠性上逐渐降低但多样性逐渐升高，样我们可以很容易把自己的知识架构在这个划分方法上。从个人知识角度，知识可以分为形而上的观点理论与形而下的事实经验。日常所见都是事实，前人所见则为历史，幻想与虚构的故事也是未来的存在，所以一个基础的形而下知识体系要有个人经验与历史，侧重对事实的准确描述，而关于未来则可单独开列，因为这类事实并不存在但不妨碍有思考的乐趣。至于形而上的东西，没必要确立经典，要按照逻辑自洽的原则去整理，包括有证据有逻辑的强理论；有逻辑无证据或弱证据的观点及个人经验；如果仅有证据没有观点，可移到形而下部分；仅有逻辑的理论是很危险的，若是科幻小说还值得看，否则不要随意吸收，因为这部分内容尚属于探索中的高风险理论，如果你不打算从政或成为企业家，可参考，但如果打算，就要考验个人决策能力了。科学探索恰恰可能也在这个地方，所以得学会用从观察与实验中提炼知识的能力，至于是否改变世界，那是你的自由。

简单说就是你可以在知识层次超过背景组后就创建一个笔记系统来整合你的知识：形而下的基础数据与案例库、历史沿革及信息检索方法与形而上的理论观点库，区分强理论与弱理论并学会总结理论。要学会把新信息整合到这个知识体系中去并持续整合，形成完整独立的知识库，这样就不容易被新思想所迷惑，总能找到位置。如同世界观一样，你自己的知识体系也会被其他人的知识体系所冲击，此时要学习别人优点来丰富自己的知识边界而不是直接彻底否定与全盘接纳，后者常发生在宗教皈依过程之中。

## 认知偏误

真实世界中人会有一些很难避免的认知偏误。这些认知规律可能来自于动物本能或进化遗留的曾经帮助人类渡过难关的思维模式，也可能来源于有倾向性的判断失误，要认识并接纳这样的人性，很多行为是无法用理性解释的。

人的本能是认知偏误的重要来源。人会厌恶风险的，如果风险从1%降到0%会比从5%降到2%给人更大的安全感，人们会为绝对安全付出更大的代价。如果感觉安全或者有人托底，人们又会倾向于冒险，人们会认为放弃一件事的损失大于得到一件事的效益，即使损失与效益的绝对量是相同的。人们天生有保守化倾向，一旦感觉会犯错就会停止尝试，但不作为本身产生的危害可能更大。这一现象可以用来设计实验，例如用抽奖手段就会比处罚手段获得更高参与度。人们天生喜欢熟悉的东西或人，会从众，做比较时会喜欢用熟悉的概念或人群做参考而不是更大的陌生人群体。人也是短视的，会看重眼前的事而对长远的事经常顾不过来，例如学术报告能给人留下印象的往往是最后几张幻灯片或者说峰终效应，毕竟人们更容易记住那些让自己产生情绪波动的事。当你的受众是普通民众时，讲他们熟悉的例子要比画饼更能被理解，有时也许熟悉的例子并不能准确反映你的观点，但传播效果要好。为了减少认知负担，人们会倾向于脸谱化一些复杂事物，给这些东西一些抽象的设定或标签，然后对着这些设定或标签发泄情绪。人们喜欢形象化的东西，能画图就不要制表。即使内容不重要，简单重复性的刺激会加深其印象。人们天生搞不清楚概率与随机事件，经常把整体中发生某事的概率理解成个人重复做会发生某事的概率，把现象的概率看成预测性反馈性概率，虽然从回归意义上也有一定合理性，但基本属于一厢情愿。同时，大多数人搞不清观点与事实，例如科研结论通常是事实但经常被解读为一种观点，事实有真假无对错带有不确定性但观点经常带有倾向性与确定性，这对科学传播影响很大。

人具备思维惯性。人们会倾向于不计后果维护自己的一致性或之前的判断，哪怕自己已经知道错了，这种思维惯性跟科学思维是反的，科学思维倾向于质疑自己之前的判断。确认偏误也是思维惯性的一种，人们会倾向于主动确认那些自己熟悉或确认过的观点形成正反馈甚至形成光环效应，例如巴纳姆效应。人们会认为好的总会是完美的，甚至会把认可观点或人身上不相关的特性甚至缺点也识别为优点进行追捧。另外，每个人的经历不同或者背景知识不同，会对相同的事实产生不同的决策或判断，也就是说思维惯性对不同的人是不一样的。研究人员不能用自己的思维惯性去设计面向别人的实验，需要更多的同理心来兼容不同想法，写论文的时候也不能假设读者能顺着你思路想问题，毕竟有些人的思路非常跳跃。说白了人会脑补，读下下面这段文字，相信有英文基础的科研人员都知道是怎么回事，但问题是里面的单词大多数都是错的。我们的大脑会把错的识别为正确的，也会同样把正确的识别为错误，一定要警惕过于符合自己价值判断的理论与现象。

> I cdnuolt blveiee taht I cluod aulaclty uesdnatnrd waht I was rdanieg. The phaonmneal pweor of the hmuan mnid, aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it dseno't mtaetr in waht oerdr the ltteres in a wrod are, the olny iproamtnt tihng is taht th e frsit and lsat ltteer be in the rghit pclae. The rset can be a taotl mses and you can sitll raed it whotuit a pboerlm. Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe. Azanmig huh? yaeh and I awlyas tghuhot slpeling was ipmorantt!

人会有逻辑自洽的倾向。这是人维持心态稳定的重要保障，人会倾向于解释一切的模糊因果理论但对概率模型及不确定性敬而远之，也会倾向于从噪音里找规律。好比一个律师打官司，他要做的就是收集事实证据形成证据链，但目的从一开始就定好了，那就是最大程度保护委托人。法庭因果看重的是叙事逻辑而不是真相本身，例如一个人随机杀人，那么其律师就要为这个行为构建行为逻辑，例如精神有问题或被别人指使。不论如何，法官或陪审团会从原因出发来量刑或定罪。然而，事实是这个人可能就是随机杀人，没有精神病史，也没有幕后黑手，但这个事实律师也好、法庭也好都会认为不可能，杀人不是意外，一定有历史或个人因素的原因，而这样的证据也可以很轻松从邻居或朋友评论中找到蛛丝马迹连成故事，可能是小时候踩死蚂蚁后笑了一下，可能是某次闲谈提到了武器，这些都是事实，但连成故事后可能杀人者都会突然发现，原来他逻辑上早就可能杀人了，甚至怀疑自己并不是随机杀人而是早有伏笔。人的记忆需要完整的逻辑连接来补充遗忘的部分，因此说的通的故事就会被认为是真实的。

但逻辑自洽经常跟事实对不上，好比一个科学家研究一个问题，他所能做的就是观察与实验，结论在观察中无法直接得出，要等数据符合统计要求了才能开展分析，经常连结论都没有而只是对之前一个观点的否定，要构建一组因果关系非常麻烦，需要反复多角度论证，如果论述不充分，科学家宁可保持未知状态也不会去任何一个数据支撑不充分的结论。这种因果观先看现象后形成论点，有时候还行不成很严谨的结论。例如病毒出现了，流病专家、基因组学专家还有分析专家都会在各自学科背景下对源头进行推测并报告不确定度，然而持法庭因果的人已经开始了审判。同样，法庭因果下人们只会采纳有利于自己的证据，但科研环境下不存在原告被告，需要同时列出实验阳性与阴性的结果，如果一组实验反复重复时只在小概率下阳性，那么这个现象不能被认为是真的。

认知偏误是所有人都有的问题，了解这些行为除了能帮助识别科研中存在的跟别人有关的问题，也能促进自我反省。通常而言，接受高等教育且从事科研的人经常会把自己的认知水平放到一个高位去跟别人交流，但事实上在犯错这件事上知识水平的预防效果非常有限。科研就是在错误中前进的，越快承认错误就能越快思考发现新的解决思路，当然也许新的思路还是错的。千万不要纠结结论的对错去评判别人，科研的重点在真假而不是对相对临时结论的价值判断。不要傲慢。
