# 数据处理 {#data}

数据处理是科研中很重要的一环，同样的数据不同的人处理会得到不同的结论。事实只有一个，但解释可以有很多，数据处理方式本身就会对解释产生影响。这里重点讨论几个常见的数据处理问题。

## 多重比较

- 多重比较问题 https://www.nature.com/articles/nbt1209-1135

- Bretz, F., Hothorn, T., Westfall, P., 2010. Multiple Comparisons Using R. CRC Press.
Gabriel, K.R., 1978. A Simple Method of Multiple Comparisons of Means. J. Am. Stat. Assoc. 73, 724. https://doi.org/10.2307/2286265

- Gelman, A., Hill, J., Yajima, M., 2009. Why we (usually) don’t have to worry about multiple comparisons. ArXiv09072478 Stat.

- Plotting of multiple comparisons? [WWW Document], n.d. URL http://stackoverflow.com/questions/2286085/plotting-of-multiple-comparisons (accessed 11.9.13).

- Rafter, J.A., Abell, M.L., Braselton, J.P., 2002. Multiple comparison methods for means. Siam Rev. 44, 259–278.
Stoline, M.R., Ury, H.K., 1979. Tables of the Studentized Maximum Modulus Distribution and an Application to Multiple Comparisons among Means. Technometrics 21, 87. https://doi.org/10.2307/1268584

- [多重比较谬误](https://zh.wikipedia.org/wiki/%E5%A4%9A%E9%87%8D%E6%AF%94%E8%BC%83%E8%AC%AC%E8%AA%A4)

## 多重检验

- p值

## 线性模型

- 从lasso到岭回归，惩罚项在回归分析中的应用
- 截断回归与缺失值处理
- 线性混合模型
- 线性模型中非考察变量的判定与消除
- 分层模型 https://www.nature.com/articles/nbt.1619
- 线性判别分析与特征发现
- logistic回归与剂量效应曲线
- 相关性分析与工具变量 https://www.nature.com/articles/nbt0309-255
- 偏最小二乘分析在结构效应关系研究中的应用

## 模型

- MCMC方法 https://www.nature.com/articles/nbt1004-1315

- 聚类与主成分分析 https://www.nature.com/articles/nbt0308-303 https://www.nature.com/articles/nbt1205-1499
- 列联表分析与流行病学研究
- 人工神经网络与黑箱计算 http://www.nature.com/doifinder/10.1038/nbt1386

- 支持向量机的回归与分类 https://www.nature.com/articles/nbt1206-1565
- 从决策树到随机森林 http://www.nature.com/doifinder/10.1038/nbt0908-1011

- 经验贝叶斯与近似贝叶斯计算（ABC）及贝叶斯网络 https://www.nature.com/articles/nbt0106-51
https://www.nature.com/articles/nbt0806-959 
https://www.nature.com/articles/nbt0904-1177
- 时间序列分析
- 结构方程模型

## 可视化

## 重采样

- bootstrap思想


