# 学术生活

## 学术出版

### 期刊论文

- 合作者人数与版本控制
- 先画图后写作
- 语言简洁可能不利于发表，但有利于传播
- 公开代码、数据、软件来提高研究的可重复性，被重复有利于提高学术影响力
- 信任合作者
- 马上动笔，拒绝完美
- 博客文章、软件包在传播上与论文一样重要，甚至更重要
- 论文由方法、数据、结果跟结论组成，先完成前三个
- 阴性结果也是结果，对其他科研人员也有参考价值，也要考虑发表，哪怕是博客发表
- 预先发表
- 投稿到你设想中读者会读到的地方
- 通过社交网络传播你的发现
- 开放获取？？？基金与影响力传播
- 延长论文的半衰期

### 会议摘要

### 专著

- 在线出版
- 允许反馈
- leanpub／gitbook／amazon kindle direct publishing／bookdown
- 按需求出版纸质版 lulu.com

### 专利

### 软件

## 学术会议

### 口头报告

- 娱乐而不是教诲
- 写给观众而不是自己
- 用所见即所得方式
- 首页有联系方式
- 大字体
- 有链接
- 对比色
- 图片文字比1000:1
- 解释图片时先说干什么用的，然后解释坐标，然后解释关键现象
- 解释公式时用文字不要用单一符号，脚标不要太多
- 注意时间

### 海报报告

### 听报告

## 审稿

- 尽快，否则不做
- 可以进行发表后审稿或公开评论
- 流程是主编确认投稿是否合乎范围，分配给专业副主编，副主编寻找审稿人
- 如果对方改了也不能达到你认为的标准，拒绝而不是大修或小修

## 学术合作

### 数据共享

### 社交网络

- 记录学科内的重要进展
- 如果个人忙不过来，可以考虑多人合作编辑或找到组织成为作者
- 跟业界联系的渠道
- 提高自己交流与可视化的能力
- 每个人每天都会在互联网上花费时间，博客是有机融合
- 互联网只关注异常、争论与胜负而不是共识，共识可以交给科普
- 质疑要比实际操作轻松
- 对自己文章要按互联网信息传播速度回复或形成论文发表来回应
- 不回复质疑会影响学术声誉
- 博客行文会影响别人对你的看法
- 构建／加入在线学术社团
- 放大影响力
- 构建趋势感
- 线上线下互联
- 多使用图片
- 谨慎介入糊涂账话题

## 讲课

- 教案与视频在线化
- 在问答社区贡献答案 quora stackoverflow reddit 知乎 果壳
- slideshare speakerdeck figshare
- mooc 课程尽量短（少于10分钟） 脸皮要厚 注意产权

## 课题组管理

- slack／hipchat
- 按项目交流
- 定期交流
- 人员管理要及时
- 分享文献
- 分享实验室内部规定

### 科研的创业隐喻

其实科研，特别是理工科科研，很像是创业过程。互动的理解这个过程有助于青年科研人员知道自己究竟在干什么。

- 投资人：政府或企业

- 公司：项目或课题

- 董事长：课题组长（PI）

- 经理：小老板或子课题负责人

- 项目经理：博士生／硕士生／本科生

- 员工：无

- idea／论文：产品

- 质检员：张全蛋，额，打错了，是审稿人

- 产品上市：论文发表

- 产品发布平台：学术期刊

- 产品未通过内部质检：论文拒稿

- 产品有销量：论文被引用

- 产品成为爆款：论文被大量引用

- 产品被媒体推荐：论文被编辑或综述点评

- 产品滞销：论文无引用

- 产品原料配料表：论文数据共享

- 产品生产流程：数据处理

- 产品被模仿：论文被重复验证

- 产品补丁：论文修正

- 产品更新换代：论文跟进发表

- 产品推介会：学术会议

- 产品退市：论文撤稿

- 公司融资：申请基金

- 新三板／创业板：申请青基

- A股：申请面上

- 路演：项目申请书

- 估值：学术影响力

- 竞争公司：研究方向

## 学术声誉

- 论文第一
- 定量化
- altmetric
- cv优化
- 跟老司机交流
- 职业规划
- 常任轨研究教授／常任轨文理学院教授／研究性教职／业界
- 常用ID 简短难重复
- 商用个人用email分开
- 线上线下一致

## 学术道德／伦理

## 案例

- 科学新闻探索 http://www.statschat.org.nz/2017/02/04/tracing-a-science-story/