# 学术生活{#life}

## 学术道德／伦理

### 剽窃

剽窃（plagiarism）包括但不限于对他人发表或未发表工作、想法、数据等的不恰当引用或故意不引用，也包括对自己发表成果的重复使用。在引述别人观点时，要做到总结转述与引用同时使用以表示对原作者的致敬。整段引用可使用引号但要根据期刊要求来做，转述不能简单做语序调整与同义词互换，要做到理解层面的叙述。对于别人在学术交流场合进行的讨论，也要进行充分引用来说明来源，学术圈里人们不会因为想法是你的而尊敬你多少，但会因为想法不是你的你却说成是自己的而鄙视你。

### 文章挂名

尽早决定且只有对文章有显著智力非物质贡献的人适合挂名，在现实中会存在索要挂名的行为但需要综合考虑。一般来说，挂名作者要至少有如下行为之一：

- 提出概念或设计
- 收集分析数据
- 撰写草稿
- 同意最终版本发表并负责

不得不承认的是有些人可能仅仅是在文章写作阶段参与，但其对文章的内容理解阐述可以让读者很简单了解文章的内容，此时是否列入作者需要综合考虑而不是单纯排斥，每篇文章都有自己的生命力而不是私产。当然请编辑润稿不在其中，因为编辑不对内容负责。影子作者或者代笔是严格禁止的。对于吉祥物作者，请知会该作者并阐明挂名风险，能成为吉祥物的资深研究人员有能力对自己的名誉风险做判断。各个领域的要求可能不同，但很简单的方法就是文章列一个作者贡献章节，详细记录每个挂名作者的贡献。

除了挂名，致谢中表示物质援助与技术援助也是一种不错的致敬方式，在感谢前，请告知他们并获取同意许可。

文章挂名的另一个问题是作者排序，常规操作是资深研究人员放在最后，第一作者是文章主要撰写人。作者排序常常由资深研究人员来决定，因为他们对全局智力贡献把握更准确，但最好做到内部透明。如果智力贡献不多，做实验最多的人有可能不被列为第一作者，对于研究生而言，请不要把体力劳动当成第一作者的保险，请一定参与数据分析与文章撰写磨练自己的科研能力。有些领域例如物理学会按字母表来进行作者排序，但并未广泛推广。个人认为比较理性的情况是作者字母排序配合致谢与贡献章节来解决挂名问题。

### 双重发表

一稿两投严格禁止，这对同行评议期刊的自愿审稿资源是浪费，也是不尊重。但双重发表在以下情况可能是允许的：

- 翻译
- 在选集中发表
- 文章受众不同
- 期刊间交流透明并对著作权无异议

### 数据造假

伪造（fabrication）是通过创造数据来论证自己想要的答案。修改图片，用仿真数据充当真实数据等方式都属于伪造。伪造可通过统计手段来检验。

篡改（falsification）是通过对真实数据进行修改来论证自己想要的答案。这种比单纯伪造要难发现，但独立实验室验证会发现问题。

### 有害研究实践

有害研究实践（detrimental research practices）指的是一些不易界定的学术不端，例如使用错误的统计方法与实验设计，故意隐瞒阴性结果及不披露利益冲突。

### 不合规

不合规（Noncompliance）指的是违法政策法规的研究，通常涉及伦理问题。

### 性骚扰

学术界性骚扰也是学术不端的一种形式，除了道德法律政策不允许外还会直接影响实验可信度。

### 伦理

广义科研伦理包括不限于正直（说话算数可信）、诚实（不弄虚作假）、透明（可披露研究非隐私细节）、能力（专业性）、合作（能与人共事进行研究）、社会责任、服从法律法规公义与责任心。科研人员不能在伦理问题上出问题，否则会断送职业生涯。

## 项目管理

### 香肠战术

- 不断切分到具体可执行
- 执行成本可控
- 执行时不思考整体，关注当下
- 转移注意力可放松，但要设计成杨白劳模式
- 分阶段有始有终

- [向后工作法](https://www.allthingsdistributed.com/2006/11/working_backwards.html) 
1、写新闻稿 
2、写 FAQ 
3、写用户文档 
4、写代码

### 风险管理

- 有应急预案设计
- 对外界环境变化有列表
- 安全优先原则

### 时间管理

- 开立多个项目，保证时间都浪费在有意义的事上
- 整体统筹进度控制与甘特图
- 增值分析
- 紧急重要四象限
- 与未来自己博弈

### 思维导图

- 构建知识体系

### 头脑风暴

- 随意去想相关答案
- 将答案按工作量与影响力进行区分
- 选取工作量低但影响力大的方案

### SWOT分析

- 列举自己技术的优势与劣势
- 列举外部环境的机会与威胁
- 对内外进行组合，设置对策，优势机会要扩张，劣势机会要补充不足，优势威胁要有预案，劣势威胁要对冲风险

### 笔记管理

- 版本控制
- 定期回顾
- [康奈尔笔记法](https://zh.wikipedia.org/wiki/%E5%BA%B7%E5%A5%88%E5%B0%94%E7%AC%94%E8%AE%B0%E6%B3%95)
- 晨间日记管理自己
- 费曼学习法，通过教或写文章总结来学

### 邮件

- 回复要快，24小时以内
- 题目要有辨识度，简明扼要
- 题目/正文要有关键词方便检索
- 一封邮件讨论一件事
- 简短，让读者有可操作性
- 时间紧急时告诉收信人无回复的结果
- 有后续追踪
- 有附件一定在正文中说明
- 提供自己联系方式
- 尽量纯文本文件
- 抄送的人没有回复义务
- 注意回复一个人还是所有人
- 秘密抄送尽量不要用
- 收到回信根据落款选择下一次名字
- 给陌生人邮件第一句介绍自己
- 第二句介绍你如何直到对方
- 不用 I wanted 或 I would like，用 I was wondering
- 可使用列表
- 避免 please
- 检查拼写
- 结尾表示感谢
- 落款可用 Sincerely，Best wishes

## 学术出版

### 期刊论文

- 合作者人数与版本控制
- 先画图后写作

  - 可视化陷阱
  - 模块化制图
  

- 语言简洁可能不利于发表，但有利于传播
- 公开代码、数据、软件来提高研究的可重复性，被重复有利于提高学术影响力
- 信任合作者
- 马上动笔，拒绝完美
- 博客文章、软件包在传播上与论文一样重要，甚至更重要
- 论文由方法、数据、结果跟结论组成，先完成前三个
- 阴性结果也是结果，对其他科研人员也有参考价值，也要考虑发表，哪怕是博客发表
- 预先发表 [资料](https://deevybee.blogspot.com/2018/06/preprint-publication-as-karaoke.html)
- 投稿到你设想中读者会读到的地方
- 通过社交网络传播你的发现
- 开放获取？？？基金与影响力传播
- 延长论文的半衰期
- [综述](https://rayyan.qcri.org)

- 回复审稿人

    - 逐条回复
    - 指明文中修改的位置

### 会议摘要

### 专著

- 在线出版
- 允许反馈
- leanpub／gitbook／amazon kindle direct publishing／bookdown
- 按需求出版纸质版 lulu.com

### 专利

### 软件

- [软件就是发表](https://simplystatistics.org/2018/05/03/software-as-an-academic-publication/)
- [JOSS](http://joss.theoj.org/)

## 学术会议

### 口头报告

- 提前到场交流
- 娱乐而不是教诲
- 写给观众而不是自己
- 用所见即所得方式
- 首页末页有联系方式
- 大字体
- 有链接
- 对比色
- 图片文字比1000:1
- 解释图片时先说干什么用的，然后解释坐标，然后解释关键现象
- 解释公式时用文字不要用单一符号，脚标不要太多
- 注意时间 1-2 分钟一张幻灯片
- 报告后写邮件感谢组织者

### 海报报告

- 减少文字描述，使用条目来概括研究
- 从左到右，从上到下的阅读顺序
- 信息图可以加分，但比较费精力
- 使用 [betterposter](https://www.insidehighered.com/news/2019/06/24/theres-movement-better-scientific-posters-are-they-really-better) 设计风格：左侧表示研究细节，中间放关键词加大加粗的结论配上论文QR码，右侧放回答问题所需要的图表，制作时间可以极大缩短，用色块来提高识别度
- 使用 [butterpoposter](https://derekcrowe.net/butterposter) 设计风格：上述风格的改进版，引入图形摘要，标题占右上1/4，右下是图形摘要，左边是模块化的高亮点或细节

### 电梯报告

- elevator pitch，一分钟甚至三十秒来报告你的研究或引发兴趣

### 听报告

- 携带名片
- 记笔记或录音，当天消化，邮件追踪
- 礼貌交流
- 提问题不要讲自己的故事
- 不要问与学术无关的事

## 审稿

- 1665年伦敦皇家学会出版《The Philosophical Transactions of the Royal Society of London》，巴黎科学院出版《Journal des Scavans》，这是最早两份学术期刊
- 1752年伦敦皇家学会意识到有些文章质量不高，开始启用同行评议
- 1830s 皇家协会正式引入同行评议来控制文章质量
- 1937年，美国国立癌症研究所首先启用同行评议来评审基金，后逐渐流行
- 审稿分为开方式、单盲（主流）与双盲三种
- 尽快，否则不做
- 可以进行发表后审稿或公开评论
- 流程是主编确认投稿是否合乎范围，分配给专业副主编，副主编寻找审稿人
- 如果对方改了也不能达到你认为的标准，拒绝而不是大修或小修
- 不要在审稿意见中推广自己的观点，就事论事
- [开放审稿会提高同行评议准确率](https://doi.org/10.1371/journal.pone.0026895)
- [审稿指数](https://doi.org/10.1021/ez5001148)

## 学术合作

学术合作有三种形式，学术圈内合作、学术圈-业界合作、学术圈-社区合作。业界合作是被允许的但会有系统偏差，集中于营利。社区合作通常需要社区配合采集数据，成果也服务于社区。跨国界合作需要遵守所有研究机构的要求才能进行，要提前打招呼，并有相关备忘。

## 利益冲突

- 影响主观判断的经济或其他利益或不公平的竞争优势
- 利益冲突在研究项目进行过程中随时会出现，要及时申报或停止项目，等待审核
- 经济利益冲突不仅包括研究人员个体与业界的利益关系，还可能是通过机构资助而存在的潜在利益关系
- 非经济利益冲突主包括确认偏误，也就研究中只发表对自己有利的结果，也包括良心冲突，如与军方合作的项目，更包括个人利益冲突，例如工作机会等
- 承诺冲突指在不同工作间存在的干扰，特别是对首要雇主（通常是研究机构）的干扰。例如一个学生为老师做研究助理的同时也在老师的公司兼职就会有承诺冲突问题，需要跟研究机构申报，而这位老师也存在学生研究成果私用的利益冲突问题
- 利益冲突会引入系统偏见、对已有研究结果的质疑、损害研究机构声誉与获得基金的机会
- 利益冲突需要提高透明度来解决，并消除利益冲突的影响

### 数据共享

- 通过学科内流行平台实现
- 一定要有文档解释编号
- 使用开源格式与许可

### 社交网络

- 记录学科内的重要进展
- 如果个人忙不过来，可以考虑多人合作编辑或找到组织成为作者
- 跟业界联系的渠道
- 提高自己交流与可视化的能力
- 每个人每天都会在互联网上花费时间，博客是有机融合
- 互联网只关注异常、争论与胜负而不是共识，共识可以交给科普
- 质疑要比实际操作轻松
- 对自己文章要按互联网信息传播速度回复或形成论文发表来回应
- 不回复质疑会影响学术声誉
- 博客行文会影响别人对你的看法
- 构建／加入在线学术社团
- 放大影响力
- 构建趋势感
- 线上线下互联
- 多使用图片
- 谨慎介入糊涂账话题
- [均值、中位数等单一数值常在媒体报道跟论文中用来指代群体，但其实牺牲了很多重要的分布细节进而产生误导，甚至让人产生被平均的感受，而直接展示整体其实并不困难，重要的是作者/研究者应放开心态，从引导读者认同自己观点转为让读者自己探索出结论](http://flowingdata.com/2017/07/07/small-summary-stats/)
- 多媒体 v.s. 文字
- 快速反馈交流
- 跨学科研究中的囚徒困境

## 讲课

### 学生如何学习？

首先搞清楚你自己学科里学习的含义，如何去掌握知识，自己在学习过程中有益的经验。学生的学习方法有深入学习、策略学习还有表面学习。了解个体学习的差异如何影响学习效果，例如前置知识、动机、学习策略还有对于学习智力能力的信仰。掌握元认知方法，掌控自己的思考过程。明白教学是承前启后的受多方面影响，要根据内容与学生调节教学方法，要知道学生对不同教学环境的应对策略。

### 如何激励学生？

- 激励就是让学生渴望或乐意做某事。

激励的理论模型：

- 期望-价值理论 学生对目标有一个期望并对这个期望有一个价值判断
- 成就目标导向理论  有些人是掌握目标导向，有些是表现目标导向
- 成长-固定思维模式 有些人认为能力可以不断发展，有些则认为无法变化
- 自我表现理论 人类三个基本需求：能力认可、归属感及自治
激励方法就是让学生提高激励的体验，例如预先教一些技术提高完成度、课前测试、让学生选择主题、分享学习经验、提供正面反馈、考核时比较灵活（6次作业取5次成绩）
在教学时要考虑作业与评价方式，学习活动，反馈还有课堂气氛。给予学生主动权，提高存在感与社交活跃度，建立对教学行为评价的持续反馈机制，记住学生的名字...
学习金字塔从下往上：记忆-理解-应用-分析-评价-创造

### 评价学习

学生学什么与怎么学经常依赖于如何被评价，评价有三种形式：
- 诊断式：小测试、涂鸦板、头脑风暴、一对一会议、思维导图还有概念测试
- 形成性：让学生提出最难懂的问题、一分钟论文、小抄、随堂测试（给出比例）、同行评议、反馈、问题集、非正式展示、进展报告
- 总结性：期中期末最终展示
- 教学目标、教学行为与反馈之间要相互有联系，给出指引，自己先完成并且对学生作业做出点评

### 课程设计

- 从教学目标、教学形式和评价三个方面入手考虑课程设计。
- 首先整理课程概念，头脑风暴选出来以后思考概念间的联系，反复思考概念间的相互关系。课程结束后可以让学生自己去绘制自己的课程地图。
- 教学目标上从学生角度出发，考虑他们通过课程知道什么、做什么以及有什么样的感受，就是从脑、心、手三个方面去设立，用强动词例如解决、设计、定义、评价而不要用知道、理解等词来设立目标。
- 评价方法参考上面评价章节
- 教学形式上明确学习时间不同于上课时间，提供知识与实践反馈，采取主动教学等策略
- 布鲁姆分类学
- 教案与视频在线化

### 互动学习

- 提高课堂参与度的组织形式，例如分组相互讨论，课程设计可以按照预热-小教程-团体活动-分享来划分时间
- 翻转课堂

### 教学理念

- 教学档案的一部分，常用来作为简历教学经历的补充。一般一页，说明三个声明，更多是理念不是行为。整理教学理念常用来整理自己关于教学的理解，作为教学的行动指南，也可以用到工作申请上去。
- 首先去思考理念的来源与如何起源，然后可以采用隐喻，例如园丁、教练、瑞士军刀，说明目标-方法-评价-改进。

## 课题组管理

### 课题组规章

- 指导方式与风格要尽早说明，实验室内部规定公开化、透明化，每年修订
- 课题组成员一定要经过安全培训，预留紧急联系人
- 人员管理要及时，新成员两轮面试，一轮课题组长，一轮课题组成员
- 新入组成员可在课题组长处领取课题组资源的账号，结题后文件夹转为只读
- 课题组正式成员必须是计划在组内学习工作超过一年的成年人，能为自己行为负责
- 课题组临时成员为短期交流人员，参与组会与一对一讨论，不考核表现
- 课题组成员应遵纪守法，学术不端直接上报开除
- 课题组原则上不申报或接受涉密项目
- 日常实时交流要与生活社交工具分割
- 按项目组织交流，原则上项目两年内必须结题，不论成败均需要在课题组网站公布署名结题报告
- 分享课题组文献库
- 提倡同龄人互相指导，自主解决问题
- 定期交流，组会分为一对一讨论与集体组会，一对一讨论两周一次，需要交进度报告存档，仅个人与课题组长参与。集体组会一周一次，每次一个人讲项目大家讨论，一个人讲文献，然后讨论实验室内部管理问题，最后可讨论科研以外问题，每学期初定下各次组会主持人
- 仪器耗材购买需在组会上提出，课题组长判断，购买记录打印存档
- 因个人失误造成的课题组经济损失如与课题组被资助项目相关，损失由课题组承担，其他则视情况由成员与课题组共同承担
- 提倡开源项目开发，无论是否与课题相关均可作为项目成果回报，但不可作为毕业项目
- 课题组科研资源优先满足组内成员项目，其他课题组使用应报备课题组长
- 禁止组内随份子钱及其他可能造成经济压力的活动
- 分析实验室工作人员内禁止使用含散发性气味的个人护理品与金属配饰，着装要符合安全标准
- 指明课题组外的资源，鼓励合作
- 课题组成员可视自身情况积极申请奖项与基金，但至少要完成一个项目后才会获得课题组推荐
- 课题组正式成员可随时向组外成员介绍课题组已公开的工作
- 开会学生一年一次机会，口头报告额外多一次，出国会议每个博士生有一次机会，申请到经费或自费的不算
- 每个学生每两年可申请一次付费培训，内容必须与科研项目有关
- 假期符合国家规定，除此之外工作日年假十天，提前一周报备，病假每月一天，假期当年用不完第二年折半累积
- 不提倡加班，提倡错时利用有限资源与高效学习工作
- 补助不低于学校同院系课题组中位数
- 在学期间生育不论男女不建议参与有机溶剂相关项目，可申请休学半年到一年
- 课题组成员如因故中断项目或学业，请尽早通知课题组长
- 文章挂名写清楚贡献，无贡献不挂名，合作方要求挂名请尽早通知课题组长判断
- 毕业生毕业最低标准为硕士主导完整完成一个科研项目，博士主导完成三个科研项目，每个项目长度原则上不超过两年，包括失败的项目
- 毕业生毕业答辩请认真准备，符合组内毕业标准不意味能顺利拿到学位，只说明课题组不会卡人
- 毕业生达到毕业标准后可自行决定毕业时间，提前半年通知课题组长，课题组长推荐信会公开在课题组网站备用
- 毕业生毕业前半年可不进行一对一讨论与集体组会，专心准备毕业相关事宜，如果需要实习请提前告知课题组长
- 毕业生交接请预留一个月时间，所有实验原始记录要完整可追踪，附有电子版或电子版摘要
- 规章最终解释权归课题组长

### 基金申请

- 基金透明度问题 http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002333
- 阶梯化基金
- 合作者
- 预算
- 评审

## 学术评价

- 定量化，论文第一 [影响因子优化问题](https://onlinelibrary.wiley.com/doi/full/10.1111/eci.13151)
- 学术评奖存在身份限制
- 影响力评价 altmetric
- [CrossRef Event Data](https://www.crossref.org/education/event-data/) 
- [预印本、开放获取期刊与社交网络互动是当前学术界的新潮流，不过也可能成为学术圈自恋的新战场，更高下载量与社交媒体转发评分有可能成为科研人员继SCI论文、影响因子与h指数后新的“优化”指数。](https://liorpachter.wordpress.com/2019/01/29/technologies-of-narcissism/)
- 青年学者压力过大
- [科学家的奖励信号](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0142537) 
- [提前发表可以提高影响因子](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0053374) 
- [题目越短引用越多](http://rsos.royalsocietypublishing.org/content/2/8/150266) 

## 案例

- [科学新闻探索](http://www.statschat.org.nz/2017/02/04/tracing-a-science-story/) 

- [华盛顿邮报根据一项研究成果写了篇科学报道，然后捅了统计学家的马蜂窝，Gelman称之为“beauty” ，因为这项研究基本把实验设计中常见的错误犯了个遍，而作为普利策奖得主的记者完全没看出来](http://andrewgelman.com/2017/09/19/2010s-never-happened/)

- [学科是存在鄙视链的，例如这位物理学家看到皇家化学会发表一篇烤面包公式的论文后不但马上发明了一个 bullshit 公式，还声称如果物理学会敢发表这种东西，自己马上放弃会员](http://wordpress.mrreid.org/2013/08/20/the-equation-for-the-perfect-equation/)

- [巫毒娃娃的PNAS](http://andrewgelman.com/2018/04/01/april-fools-post-dead-serious/)

- [数学家关于进化的争论](https://liorpachter.wordpress.com/2018/09/17/mathematics-matters/)

- 公民科学家

-  [发表一篇好还是多篇好的讨论](https://deevybee.blogspot.com/2018/07/one-big-study-or-two-small-studies.html)