# 学术生活{#life}

现代科研会影响渗透到科研人员的日常生活之中，本章会讨论下学术生活中一些重要的议题。学术道德与伦理是第一位的，在职业化的科研中有一票否决的权力。邮件是最常见的学术交流工具，我们会讨论下一些基本礼仪。学术出版、学术会议与审稿则是最正式的学术交流方式，我们会讨论下其中的注意事项。之后会讨论下学术合作的问题与利益冲突问题。课题组管理可能是现代科研行业里最容易忽视的一环，这里会介绍下课题组管理的注意事项。最后，讲课也是学术生活的重要组成部分，需要普及一些基本的教学理念或方法。

## 学术道德／伦理

学术道德与伦理经常是默认科研人员都知道但其实新闻的教育效果要大于课堂教育的论题。这里从剽窃、文章挂名、双重发表、数据造假、有害研究实践、合规性、性骚扰及伦理方面来介绍下相关内容。

### 剽窃

剽窃（plagiarism）包括但不限于对他人发表或未发表工作、想法、数据等的不恰当引用或故意不引用，也包括对自己发表成果的重复使用。在引述别人观点时，要做到总结转述与引用同时使用以表示对原作者的致敬。整段引用可使用引号但要根据期刊要求来做，转述不能简单做语序调整与同义词互换，要做到理解层面的叙述。对于别人在学术交流场合进行的讨论，也要进行充分引用来说明来源，学术圈里人们不会因为想法是你的而尊敬你多少，但会因为想法不是你的你却说成是自己的而鄙视你。

### 文章挂名

尽早决定且只有对文章有显著智力非物质贡献的人适合挂名，在现实中会存在索要挂名的行为但需要综合考虑。一般来说，挂名作者要至少有如下行为之一：

- 提出概念或设计
- 收集分析数据
- 撰写草稿
- 同意最终版本发表并负责

不得不承认的是有些人可能仅仅是在文章写作阶段参与，但其对文章的内容理解阐述可以让读者很简单了解文章的内容，此时是否列入作者需要综合考虑而不是单纯排斥，每篇文章都有自己的生命力而不是私产。当然请编辑润稿不在其中，因为编辑不对内容负责。影子作者或者代笔是严格禁止的。对于吉祥物作者，请知会该作者并阐明挂名风险，能成为吉祥物的资深研究人员有能力对自己的名誉风险做判断。各个领域的要求可能不同，但很简单的方法就是文章列一个作者贡献章节，详细记录每个挂名作者的贡献。

除了挂名，致谢中表示物质援助与技术援助也是一种不错的致敬方式，在感谢前，请告知他们并获取同意许可。

文章挂名的另一个问题是作者排序，常规操作是资深研究人员放在最后，第一作者是文章主要撰写人。作者排序常常由资深研究人员来决定，因为他们对全局智力贡献把握更准确，但最好做到内部透明。如果智力贡献不多，做实验最多的人有可能不被列为第一作者，对于研究生而言，请不要把体力劳动当成第一作者的保险，请一定参与数据分析与文章撰写磨练自己的科研能力。有些领域例如物理学会按字母表来进行作者排序，但并未广泛推广。个人认为比较理性的情况是作者字母排序配合致谢与贡献章节来解决挂名问题。

### 双重发表

一稿两投严格禁止，这对同行评议期刊的自愿审稿资源是浪费，也是不尊重。但双重发表在以下情况可能是允许的：

- 翻译
- 在选集中发表
- 文章受众不同
- 期刊间交流透明并对著作权无异议

### 数据造假

伪造（fabrication）是通过创造数据来论证自己想要的答案。修改图片，用仿真数据充当真实数据等方式都属于伪造。伪造可通过统计手段或其他技术手段来检验，两个检验原则是1）真实数据不太可能是完美的与2）假的数据比真数据更有目的性。

篡改（falsification）是通过对真实数据进行修改来论证自己想要的答案。这种比单纯伪造要难发现，但独立实验室验证会发现问题。篡改数据可以从制度上来规避，例如原始数据第一时间备份及保留数据处理软件的日志等。

### 有害研究实践

有害研究实践（detrimental research practices）指的是一些不易界定的学术不端，例如使用错误的统计方法与实验设计，故意隐瞒阴性结果及不披露利益冲突等手段。针对有害研究实践目前并没有很好的应对方法，但可以从基金资助角度要求研究的透明度，除了论文也要公开相关报告。

### 合规性

不合规（Noncompliance）指的是违法政策法规的研究，通常涉及伦理问题。合规性具备文化差异，确实有些研究在某些国家不容易开展而另一些国家则限制不多，这些在跨文化学术交流时一定要注意。

### 性骚扰

学术界性骚扰也是学术不端的一种形式，除了道德法律政策不允许外还会直接影响实验可信度。性骚扰包含异性与同性间涉及使用显性或隐性的性暗示的骚扰。性骚扰不仅仅包括行为上骚扰，通过口头欺辱、威胁或承诺换取性好处也属于性骚扰。

研究场合如果遇到性骚扰请上报，绝大多数公司或研究机构都会有专门负责的部门例如人事部门、妇联或工会来处理相关问题。鉴于报导出的性骚扰只占真实发生的性骚扰事件的一小部分，查实后一般都是从严处理行为不当的人。

### 歧视

歧视很多时候属于经济问题。很多运动过后会有很多人口头上表示支持反歧视但行为上依然我行我素，这样的运动主要是忽视了歧视行为背后的利益。生活在移民国家或城市的人则主要存在先来的对后来的歧视，先来的人通常垄断了移民国家或城市的话语权与价值观，在经济与政治上占有优势。美国的白人清教徒对后来的黑奴就存在这种历史性歧视，但区分先来与后来人的不仅仅是种族，还可能是地域，例如历史上上海本地人就对从事相对底层工作的苏北人有过长时间的歧视。经济上既得利益集团会给自己找些有门槛的标签（例如种族、地域、信仰、性别、职业等）来维护自己的利益并合理化这些歧视行为，常见的借口就是遗传差异或生理差异，但这些说辞并不被科学研究支持。现代社会的机器化大生产也基本抹平了很多职业的生理差异，但总会有人使用这些过时且迂腐的观点来为自己的歧视行为辩护。即使是生活在单一民族国家或城市的人也会因为一些文化民俗产生一些标签化偏见，落实为行为也属于歧视。例如招聘过程中对血型、星座、生肖、外貌等的偏好。现代社会中会不断生成新的歧视标签，因此反歧视的努力也不能间断。

学术界也存在歧视，不过很多人无法意识到自己的言语与行为对别人是一种歧视。有些科研人员会在招生时歧视学历与性别，但说到底都是为了维护自己利益最大化并确保课题组风险最小化。要抵制歧视行为，指望个人高风亮节的效果很差，应该构建兼顾机会公平的体制。不过，绝对的公平过于理想，甚至不同人立场不同对公平的理解也不一样。以性别歧视而言，利益受损的性别会去主张不公平的受损待遇但却会忽视自己已经受益的待遇，这样的主张会让另一方感觉无理取闹，等双方都带着情绪立场来辩论必然谁也说服不了谁，最后歧视问题没解决反而加重了人群分裂与对立。一旦出现一方要坚决打倒另一方且双方互相指责歧视，那么歧视就只是一个发泄情绪的借口而不是可以解决的问题了。

歧视问题必然与社会发展长期共存且不断发展，经常是一类歧视伴随发展消失但又出现了另一类歧视，反对歧视的核心应该是换位思考而不是抓紧区分敌我后发泄情绪。任何只取悦部分人利益的所谓反歧视解决方案必然会被另一部分人抵制，临时疏导双方情绪并不能真正解决问题，调和利益达成共识才有可能消除歧视根源。当然，这句在很多事实面前属于正确但无用的废话。

### 伦理

广义科研伦理包括不限于正直（说话算数可信）、诚实（不弄虚作假）、透明（可披露研究非隐私细节）、能力（专业性）、合作（能与人共事进行研究）、社会责任、服从法律法规公义与责任心。科研人员不能在伦理问题上出问题，否则会断送职业生涯。

此外，伦理问题更多是社会问题而不是科学问题，可以用科学方法来研究伦理问题但伦理问题不一定有明确的答案。歧视与偏见问题是科研中经常遇到的，同样的问题在不同的知识背景描述下会给第三方产生不适，此时要尽量采用中性描述而不是渲染情感。在交流时请尽量提前划定双方的底线，只讨论双方有讨论空间的问题而没必要在缺乏证据的基础上对观点发表意见。

## 邮件

邮件回复要快，工作日24小时以内，节假日不发邮件。题目要有辨识度，简明扼要，题目/正文要有关键词方便检索。一封邮件讨论一件事，简短，让读者有可操作性，给出决策问句。时间紧急时告诉收信人无回复的结果，有后续追踪。有附件一定在正文中说明。邮件签名提供自己联系方式。尽量用纯文本文件，开拼写检查。明白抄送的人没有回复义务，秘密抄送尽量不要用，注意回复一个人还是所有人。收到回信根据落款选择下一次名字，给陌生人邮件第一句介绍自己，第二句介绍你如何直到对方，不要用带有压迫性的 I wanted 或 I would like，用 I was wondering。可使用列表来分条目讲问题。避免用 please。结尾表示感谢，落款可用 Sincerely，Best wishes，Thanks。

## 学术出版

学术出版是学术工作的重头戏，期刊论文、会议摘要、专著、专利还有软件都属于学术出版的内容，下面将详细讨论这几类出版物的注意事项。

### 期刊论文

写论文的时间分配不是一个可以计划的东西，从一开始提出假设，设计实验，执行实验到数据分析，这些工作都不算在写论文的时间里，但这些阶段如果没有文献与实验结果的积累，最后的论文写作会变得无比痛苦。这里假设前期工作是比较理想的。

第一阶段是组织材料，这一阶段是最重要的，大概占论文写作70%的时间。论文边写边找文献支持会很乱，所以同一时间就做一件事，那就需要先组织资料。而组织资料是要有一个分类系统，也就是说看到一篇文献，你脑中要能把它定位在你论文中出现的地方，例如前言或讨论。这里我建议尝试用一下思维导图，你的核心想法在中间，发散出例如背景，方法，类似研究等子话题，相当于使用树形目录组织文献。之后，你可以关上电脑，找张纸把你的写作大纲列出来，想出每一段的主题与结构。当你做完这些工作后，文章就剩下写这一个步骤了。这个过程可以贯穿到数据分析之前的所有步骤，因为脑子随时可以思考问题。

前一阶段如果做好了，写初稿并不困难，用10%的时间。初稿不要一上来就力求完美，尽量按顺序吧想法说清楚，重点看逻辑，句型什么的可以放放，一气呵成，要马上动笔，拒绝完美。然后进入下一阶段，如果纠结写作细节会影响整体内容的思考，先把你的故事说出来，然后再润色。

之后的修改阶段可以多花时间，约20%，主要针对表述。大声把论文读出来，看跟读是不一样的，能发现不少问题。检查动词的使用与语态的使用，其实上篇讲的东西就是为这个阶段准备的。然后你可以找一个同专业不同方向的同事读一下，因为你的文章更多被这些人读，所以他们能否读懂决定你的表达能力，读不明白一定就是你没写好，至于文章档次在你设计实验时基本就定型了。如果有条件的话最好找个专业编辑给你改改。感觉不会表述可以去查曼彻斯特大学的[Academic Phrasebank](https://www.phrasebank.manchester.ac.uk/)来找模版句式，想换个同义词就到网上去搜索，一般而言你不会是第一个遇到这个问题的。

然后是检查阶段，就是查缺补漏，主要针对校对等最后期的工作。例如编号前后一致，参考文献的指代。这里要注意的是引用文献一定要看原文，转引不靠谱，因为很多发表的文章引用上并不见得没错误。

时间分配的核心在于细化步骤，理清思路，一段时间解决一个问题而不是同时解决表述、语法、引用等多方面的问题。优先考虑内容的表达，然后才是形式的修改，做到有条不紊，平稳写作。

一般的写作顺序为图表->结果->方法->前言->讨论->结论->摘要，内在的逻辑是当你实验数据处理完了，首先得到的就是分析数据的产品——图表，结果部分其实是围绕图表转的，所以这两部分趁热打铁最先完成。然后就是遵循由难到易的过程先把方法写了，这部分也不痛苦。然后就是前言，这部分就是小综述，文献看到位就可以写出来。最后的重头戏就是讨论，这部分最难写，逻辑要求最高，写完了结论与摘要就自然而然写出来了。按这个顺序你可以较为流畅的写完初稿。

在写文章上，图表是最直观也最应该先做出来的。你的工作浓缩在一张图里是最容易给人留下印象的，正所谓一图胜千言。对图表的要求则是要能独立的说明一个问题，而且越少越好。现在很多期刊要求有图形摘要其实就是方便读者快速抓住核心想法的，每一张图都尽可能漂亮且说明性强，不是单纯罗列数据而是尽可能展示数据的规律。

然后是结果，很多期刊是要求结果与讨论分离的，这个时候结果的目的就在于描述实验结果的现象。需要注意的是这个部分不等于描述原始数据，你需要在结果部分展示上面一步做好的图表并指出简单的关系与趋势。需要注意的是在图表中出现的数据除非特别重要就不要写出来了，图上不方便标明的数据在结果中要有交待。一定记得描述你的对照实验，让结果部分在逻辑上没有漏洞。此外，结果中提到的显著差异一定要是统计学上的而不是看出来的，也不要在结果里讨论方法与他人观点，这些内容有其他章节负责。结果就是描述你的实验结果，用过去式，但图表的解释用现在式。

之后是方法，这部分没什么好说的，实验设计要严谨表述。如果按文献方法做要引用出处，自己设计的最好给个流程图，不要让读者读着太痛苦。可用过去式与被动语态，统计方法记着要写清楚了。

之后是前言，这部分可以看作小综述，但实际写作也有其逻辑结构，一般写三段，按照已知-未知-假说的结构写。也就是说，写一下关于研究对象你知道什么，不知道什么，你提出的假设是什么。这样比较符合人们认识事物的过程且不乱，用语要高度概括，不要纠结于细节，那是写综述要注意的，这样从大到小收敛到你的工作上下面就可以讨论你的文章了。

之后的讨论这是最难写的部分，也是最自由的部分，与前言相反，这部分你要能把你的发现定位到大背景中。一般的逻辑结构是先回答你自己提出的假设的结果，然后用你的数据说明结果，之后广引文献来证明你的结果并讨论与其他研究结果不同的原因，也就是展开讨论未知，最后把你的结果定位到已知的位置看能否说明一些问题。值得注意的是不要过度演绎你的实验结果，也要讨论下局限性与前景。在这一部分你要着重使用上篇中提到的三个原则，结论强劲有力，不要遮遮掩掩，这些遮掩会让审稿人感觉你的结果不可靠且对学科发展没意义。

之后结论这一部分简短一点，把你文章的亮点展示出来就OK，同时可以用一句话做出展望。

最后写摘要，摘要部分其实就几句话，一句话说背景，一句话提出自己的假设或问题，一句话描述实验方法，一句话给出最核心结果，然后给出一句话结论并加上合理的推测。当然你也可以按照你自己的思路去写，但要记清楚，很多人看文章只看摘要的。把它放最后的意义也在于能够让你很好的去总结自己的文章。

目前很多期刊要求注明经费来源与个人贡献，很多还对数据共享与可视化有额外要求，请投稿时一定核查清楚。在论文挂名与致谢上，有实际贡献特别是论文修改与实验的智力贡献才可挂名，否则属于致谢。

写作顺序的考量其实就是一个从简单到复杂的考量，先处理简单的部分的优势在于如果你上来就去讨论，很可能脱离实际数据而瞻前顾后。

此外，论文写作也有一些其他的注意事项。首先，一定要注重精简，也就是写文章要有读者的视角。语言简洁可能不利于发表，但有利于传播。不考虑读者一味堆砌专业术语与高级句式，只会让人读不懂，在审稿人看来自然就是英文很烂的表现。高级句式与词汇是锦上添花的东西，没有通俗易懂的锦，只会让人看花眼。科技论文不代表就一定要从句套从句，这样的句子属于中国特色的阅读理解。老外（北美多于欧洲）都喜欢直来直去，论文表达内容优先，句式什么的可以放后面考虑。先看明白了再说别的，看不明白不是故意虚掩就是表意不清，一般审稿人会按后者对待写到审稿意见上。而且要有力度有自信的说出来，不去绕弯子。要是不习惯，可以先写成繁冗模式，然后精简。

常见的可精简词语：

- 无意义引导词如As it is well known
- 空洞语句如basic tenets of
- 不必要的缩写与专用名词如 miR
- 重复性词语如illustrate/demonstrate
- 副词如very, really, quite, basically, generally, etc.

少用否定句。否定他人和自己都不是有自信的表现。少用there is/are。主语提前，要不然读者找起来费事，给读者找麻烦就是给自己找麻烦。不用没意义的介词。that跟on，读者会自己脑补的，在理解上有没有没区别就精简掉。

另外是可以使用主动语态的简单句的。被动语态会省略主语，显得不负责任。而使用主动语态会让文章更为生动真实，易于阅读且也是一种认真负责的态度。事实上越是高端的期刊越不计较这事，science就明确同意使用第一人称，而DNA被发现的那篇经典论文（发表于nature）的第一句也使用了第一人称。主动语态可以用在除方法描述外的任何场合，可间歇配合被动语态让文章更流畅。而实验方法的描述使用被动语态则是因为怎么做比谁做了更重要，同时关注方法部分的读者实际只关注一些关键词，写生动没多大意义。

使用强有力的动词。把中性动词+形容词改为动词，这样不罗嗦，少用to be，用了to be就可参照上面改成一个动词，简化句式。不要把动词改成动名词，可结合主动语态理解。主语跟动词要靠近，不要让读者找动词，不易于表意。在动词时态选择上，过去式描述自己的实验结果，一般式描述继承或验证过的事实与结论，未来式写展望。

标点符号也不仅仅用逗号与句号。分号用来表示一个句子的从句，有主谓语，有强调的效果，也可用来连接两个短句。作为内标点分隔清单，在冒号之后使用（冒号是colon，分号是semicolon）。括号表解释，可去掉不妨碍理解。冒号表示清单（至少三个）、结论、详述、引用与解释。破折号表示强调、定义与描述。列举超过三个项目时用逗号分割，最后一个项目前加 and 。

论文里出现数字时，个位数直接用英文，超过10就写数字，句子开头不能是数字，可以调整语序规避掉。

首字母大写大多只出现在句首或缩写里，后者需要在摘要或正文第一次出现的时候给出全称，这里摘要要当成与正文不同的单独文章来处理缩写。图或者表需要首字母大写，例如 Figure 1 这类。另外星期几、月份还有国籍也需要首字母大写。这类问题一般写作软件的拼写检查能发现。

论文中分段很重要，分段不清表意不明。论文写作中，最好一个段落解释一个问题，每个段落不超过5句。一般第一句是主题句（读者有时候只看这一句），然后展开讨论，总结不总结看论述长度，但最好强调下自己最得意的发现。一个段落一定要有内部逻辑结构，或平行或递近，读起来会明了。也许这看起来像是八股文，但论文不是文学作品，让读者快速明白你的意思是最重要的。过渡词很有必要时再用，转折用but就够了。说到底，标点分句子，段落分文章。在这个分割过程中一定有理有据，读起来不突兀。

论文写作时要进行版本控制，不要多人同时离线修改，可以在线同步修稿。论文相关的代码、数据、软件要公开，被重复有利于提高学术影响力。博客文章、软件包在传播上与论文一样重要，甚至更重要。阴性结果也是结果，对其他科研人员也有参考价值，也要考虑发表，哪怕是博客发表。论文也可采用[预印本](https://deevybee.blogspot.com/2018/06/preprint-publication-as-karaoke.html)（会有简单的技术审核）与开放获取来提高影响力，前者要选对服务器，后者要资金充沛。值得注意的是预印本是在同行评议前的版本，同行评议后发表前未排版的版本叫做作者接受手稿，这个只能在正式发表后依照期刊政策在个人或研究机构网站公开。但不论如何，这些版本的稿件都要给出正式发表稿件的链接。选期刊可以通过自己的引用文献来源期刊来选，投稿到你设想中读者会读到的地方，可通过社交网络传播你的发现，延长论文的半衰期。发表难度一般排序是全学科综合期刊（CNS）> 大学科综合期刊（JACS） > 子学科综合期刊（AC） > 子学科专业期刊（JASMS），伴随读者越来越广泛，研究内容的难度与重要性不断上升，很多方向因为公众关注度不高，所以子学科综合期刊可能就是最难发的了，想出圈得依赖对全学科研究前沿的把握。如果实在不清楚期刊投哪里，也可以通过文本分析 biosemantics 在线[查询](https://jane.biosemantics.org/index.php)适合的期刊。在拿到审稿意见后，要逐条回复且指明文中修改的位置，行文要礼貌，尊重审稿人的努力。

在审稿人推荐上请遵守回避原则。同一研究机构的人要回避；过去三年内有过学术合作的人要回避；论文项目的顾问要回避；有直接或间接利益冲突的要回避；恶性竞争对手要回避但也可以挑战；家庭成员、导师、指导过学位论文的学生、商业合作伙伴要回避。基本上你的稿子会被送到你不认识的人手里，也有小概率送到你的熟人手里，但大方向是出圈，小圈子互相捧成不了大气候。

此外，也可以参考美国临床化学协会的写作[指南](http://www.aacc.org/publications/clin_chem/ccgsw/Pages/default.aspx)来进行系统的学习。

### 会议摘要

不能全是已经发表的成果，除非被邀请做某个主题的报告。摘要可以是不完整未验证的结果，但要在开会前有明确结论，也可做出一定内容或结论修改。会议摘要的准备与期刊论文摘要的准备类似，但可以保留一定的开放性。

与会议摘要相关的一种出版物是会议论文。在计算机等学科里会议论文的影响力大于期刊论文，然而在其他学科里，会议论文可能影响力有限，甚至是没有正式同行评议流程的，不能简单把自己学科的评价标准放到其他学科里套用。

### 专著

现代化的学术专著一般允许在线出版，在线反馈，持续改进。专著要有良好的构架而不是简单的研究堆砌，要让读者在阅读过程中完整理解某学术方向的历史、现状与未来研究方向。

现在存在一种专著事实上是研究论文的合集，有的有同行评议过程，有的编辑直接把关，很多论文可能存在重叠与矛盾。另外一类专著是需要有人统筹校稿，各章节间逻辑结构比较强，这类专著很可能来源于课程讲义。但也存在一些人为了评职称凑学术成果，照搬翻译别人教材还自费出版形成所谓专著，这属于学术不端，但更深层次还是评价体系有漏洞。

### 专利

专利可分为外观设计、实用新型与发明三类。如果打算将研究成果转化为专利，一定要在论文正式发表前处理好申请相关的事。一般而言，一旦论文正式发表，就相当于进入公共知识领域，此时申报专利就已经晚了。此外，申请专利跟专利授权中间是一段时间的，专利授权后也需要交年费来维护专利权，如果欠费就视为放弃专利权。同时，任何人或机构都可以申请将已经授权的专利无效化，此时发明人是需要做出答复的，如果什么也不做，专利权很可能就被视为无效了。

这里要清楚，专利并不是通过授权阻止技术流动，相反，通过专利发布的技术是有利于技术流动的。你只要付费就可以用到某项技术，比自己琢磨效率高多了而且专利保护期过后技术就完全公开了。同时，真正关键的技术反而属于技术秘密而采用最原始的保密方法来维护技术独占性，例如可口可口的配方，一旦你申请大家就都知道细节了，能买到的技术都不贵。

### 软件

伴随信息科学及计算机科学对几乎所有学科的渗透，越来越多的研究可以通过计算机模拟或建模来进行。此时，开发科研用软件的贡献很多时候是大于写研究论文的，[软件就是发表](https://simplystatistics.org/2018/05/03/software-as-an-academic-publication/)，软件可以加入参考文献。其本身也可以被当成期刊论文来直接引用例如[JOSS](http://joss.theoj.org/)。此外，软件也可以申请著作权保护。

现代科研一定要重视软件，特别是开源软件的开发。软件对于科研效率的提升是非常大的，掌握软件开发这个技能对于现代科研人员而言逐渐从加分项变成了必选项。开源软件的推广也有利于知识的公开透明，而且当前开发开源软件并不代表对开发者毫无收益，很多开源社区通过咨询等商业模式同时做到了公开透明与盈利。本书的附录一提供了常见科研用软件工具的推荐。

## 学术会议

学术会议是学术生活中比较有意思的一环，到一个陌生的城市作报告顺带游玩算是科研人员的某种福利。这里会对学术会议不同场景的注意事项进行概述。

### 口头报告

口头报告一般20分钟而人的语速一分钟200字，一般报告时间控制在15分钟左右，所以如果要准备讲稿，3000字足够了，毕竟语速要慢才能达到交流效果。而一篇学术论文的文字大概5000字以上，所以口头报告内容如果是一篇论文要精简到60%的量，而涉及多篇论文则更需要压缩，内容之间要有逻辑关系来连接。一般分为背景介绍、提出科学问题、展示数据结果、给出结论、展望（不超过三条）、致谢这几步。其中科学问题一定要说清楚，结论要分条简洁有力，观众搞清楚问题与结论就算是很不错的报告了。

在报告的用语上，根据会议类型不同要选不同的术语。如果你去自己研究方向的小会议或课题组组会，术语大家都懂，大可以用缩写或专业术语。如果你去的是某个具体研究方向的会议，那么背景可以少说点，因为听众可能都知道，重点讲自己解决问题的方法。不过你去的是某个以方法为中心的会议，那么可能要多花时间讲问题本身的背景。如果你去的是综合性会议，那么即使是分会场，也得少用术语多用通俗易读形象化描述。如果你是做大会报告，绝对不能讲你自己单一文章的工作，要从学科发展逻辑下组织内容，可以标明出处后把同行内容放进来，此时听众希望听到更高视角下更长远的展望，不过这类报告属于屠龙术，绝大部分研究人员是没机会做这种报告的，但你可以练习这种视角。

做口头报告一般需要提前到场交流，而且很大概率能认真听你报告的就是这些人。会议期间要跟主持人保持良好联系，这是扩展影响力的好机会。报告内容可以酌情加入娱乐化内容，例如笑话或新闻，不要搞成教诲。报告内容写给观众而不是自己，要用所见即所得方式。保持90%的时间与观众进行眼神交流而不是对着天花板或屏幕，这活语音助手做的比你好。幻灯片首页末页有联系方式，因为这可能是展示时间最长的两张幻灯片。要用大字体，高对比色，能用图片别写文字，解释图片时先说干什么用的，然后解释坐标，然后解释关键现象。解释公式时用文字不要用单一符号，脚标不要太多。注意时间 1-2 分钟一张幻灯片，报告后写邮件感谢组织者。

报告都有提问环节，记性不好就带个笔记一下。另外回答问题要诚实，做了就是做了，没做大方说没做就可以。如果是因为提问者误解产生的问题，可以说过会下面交流而不是浪费时间解释不相关的问题。另外对于有些可预期的问题可以事先准备幻灯片。

### 海报报告

海报报告是非常好的锻炼机会，你可能要在两三个小时里把同一段内容重复七八遍。要减少文字描述，使用列表来概括研究。遵守从左到右，从上到下的阅读顺序。做信息图可以加分，但比较费精力。可以使用 [betterposter](https://www.insidehighered.com/news/2019/06/24/theres-movement-better-scientific-posters-are-they-really-better) 设计风格：左侧表示研究细节，中间放关键词加大加粗的结论配上论文QR码，右侧放回答问题所需要的图表，制作时间可以极大缩短，用色块来提高识别度。也可以使用 [butterpoposter](https://derekcrowe.net/butterposter) 设计风格：上述风格的改进版，引入图形摘要，标题占右上1/4，右下是图形摘要，左边是模块化的高亮点或细节。

做海报报告可以准备一页纸的小宣传页面，如果有人感兴趣可以通过这个找到你的联系方式与最直观的结果图表。

### 电梯报告

电梯报告（elevator pitch）指用一分钟甚至三十秒来报告你的研究或引发兴趣，跟同行交流要提前准备一套，让别人能快速了解你的研究并留下联系方式。可在开会前邮件提示可能见到的人，这样直接开口不尴尬。电梯报告只需要说明需要解决的问题与结论，对方感兴趣会给你额外时间讲过程。

### 听报告

听报告要携带名片，要记笔记或录音。当天晚上回住所消化，用邮件追踪。交流要礼貌，提问题不要讲太多自己的故事，另外不要问与学术无关的事。

### 主持报告

如果你需要主持报告，那么一定要仔细准备，事先联系好进行报告的人。一般而言，你需要准备介绍分会场的几句话并在下一个报告开始前介绍报告人与报告题目。另外，主持人最重要的作用是控制时间，提醒报告人剩余时间，另外就是提问环节，如果没人提问可以自己提问，如果问题过多可以说场下交流。报告结束后要准备几句结语，之后可以发信感谢报告人的报告。

## 审稿

审稿是学术交流的重要一环。1665年伦敦皇家学会出版《The Philosophical Transactions of the Royal Society of London》，巴黎科学院出版《Journal des Scavans》，这是最早两份学术期刊。1752年伦敦皇家学会意识到有些文章质量不高，开始启用同行评议。1830s 皇家协会正式引入同行评议来控制文章质量。1937年，美国国立癌症研究所首先启用同行评议来评审基金，后逐渐流行。审稿分为开方式、单盲（主流）与双盲三种。开放审稿会提高同行评议[准确率](https://doi.org/10.1371/journal.pone.0026895)，可以进行发表后审稿或公开评论来进行学术交流。不过盲审也有优势，例如双盲审稿会[提高](https://www.sciencedirect.com/science/article/pii/S0169534707002704)女性审稿人的影响力，且盲审可以让审稿人更自由发表批判性意见。

审稿流程是主编确认投稿是否合乎范围，分配给专业副主编，副主编寻找审稿人。审稿人审稿要尽快，否则不做。如果对方改了也不能达到你认为的标准，拒绝而不是大修或小修。不要在审稿意见中推广自己的观点，就事论事，目的是提高研究质量，把一个科学问题搞清楚而不要掺杂个人情绪。如果你跟稿件作者有利益冲突但作者没有把你列成需要回避的审稿人，请联系编辑拒绝审稿，不能把审稿作为打压手段或牟利工具。请牢记审稿是为学术内容负责的，优质但有瑕疵的内容请帮助作者把内容理顺，提高读者也就是学术圈对内容的理解，即使文章最终无法发表在投稿期刊，但如果达到学术发表标准就应该给出详尽的意见与建议，使作者能从审稿中收益而不是简单给出判断而不给任何具体理由，这样的无效审稿意见既不能帮到作者也会给编辑留下负面印象，不如直接不审稿。

审稿意见有很多种格式，有的期刊会用问卷或量表严格限定审稿内容，不过更多的期刊还是会采用相对自由的格式。一般来说，审稿第一段要告诉编辑这篇稿件的概要来表示你读懂了，然后要说明是否符合期刊收稿范围，如果不在期刊收稿范围，可建议一些其他期刊，最后一句给出你的参考意见，基本就是直接接受、小修、大修及拒稿这四类。审稿意见第二部分是给出文章的主要问题，这些主要问题通常是决定你主要审稿意见的内容，例如实验设计是否合理？文章结构是否需要调整？结论是否全面？创新点是否吸引人？通常大修跟拒稿都是需要这一部分内容的。审稿意见的第三部分是文章的具体小问题，例如错别字、表述不清、图片标题内容不全等，这些小问题通常不影响文章是否接收，但也必须从严谨角度给出解释或修改，一般用条目方式给出，给出对应的行号，一般大修、小修跟拒稿都有这部分。此外，有些期刊可以留给这让编辑看的内容，请在此部分注明是否乐意继续对返修文章审稿，也可以给出你认为作者不应知道的评论，例如对提交审稿意见比较晚致歉或可能存在的利益冲突等。

二审或更多轮审稿意见更多关注主要问题是否解决，也可以提出新的质疑，直到疑虑全部消除。不过稿件是否接收的决定权在编辑，编辑也可能忽视掉你认为关键的意见，此时如果你认为不合理请联系编辑或对稿件进行发表后的公开审稿提出质疑，学术争论不会因为文章发表就停止，相反，重要文章发表往往是新的学术争论的起点。

## 学术合作

学术合作有三种形式，学术圈内合作、学术圈-业界合作、学术圈-社区合作。学术圈内合作要在合作初期就谈好项目及相关论文的署名及责任问题，要留下邮件交流的证据，省的开始大家口头承诺都挺好，后面翻脸不认人。学术合作一定要谨慎，特别是研究内容有经济利益时一定事先跟机构里相关部门负责人打招呼做备案，否则出事了可能全都是个人责任，机构爱莫能助。跨国界合作需要遵守所有研究机构的要求才能进行，也要提前打招呼，并有相关记录可查询。总之，学术圈内合作不能太草率，如果自己感觉拿不准就去咨询下研究机构里的资深科研人员，听听故事也是受教育的一种方式。

业界合作是被允许的但会有系统偏差，集中于营利项目，需要在相关学术论文里注明利益冲突。跟业界合作拿到的横向经费钱好花但业界是一定要看到收益的。一定要在签合同前找研究机构的相关部门例如科技处去仔细审读合同，当然横向经费一般研究机构也要抽管理费的。

社区合作通常需要社区配合采集数据，成果也服务于社区。这类合作往往是带有公益科普性质的，社区提供经费可能性不大，但是能提供劳动力。例如你打算用一个你开发的模型通过终端水样推断小区自来水管网的维护情况，通常来说挨家挨户采样是不现实的，这时候就要跟社区物业或业主委员会商量，如果他们能提供测定需要的水样，你就可以给社区提供一份免费水质报告与管网维护建议。合作的类型有很多种，并不是每一种都需要钱来衡量，研究人员要学会资源互换的思路来进行研究。

## 利益冲突

利益冲突影响主观判断的经济或其他利益或不公平的竞争优势。利益冲突在研究项目进行过程中随时会出现，要及时申报或停止项目，等待审核。经济利益冲突不仅包括研究人员个体与业界的利益关系，还可能是通过机构资助而存在的潜在利益关系。非经济利益冲突主包括确认偏误，也就研究中只发表对自己有利的结果，也包括良心冲突，如与军方合作的项目，更包括个人利益冲突，例如工作机会等。承诺冲突指在不同工作间存在的干扰，特别是对首要雇主（通常是研究机构）的干扰。例如一个学生为老师做研究助理的同时也在老师的公司兼职就会有承诺冲突问题，需要跟研究机构申报，而这位老师也存在学生研究成果私用的利益冲突问题。利益冲突会引入系统偏见、对已有研究结果的质疑、损害研究机构声誉与获得基金的机会。利益冲突需要提高透明度来解决，并消除利益冲突的影响。

### 数据共享

数据共享要通过学科内流行平台实现，一定要有文档解释数据里编号的含义并使用开源格式与许可。数据共享一定是可被他人理解的共享，如果仅仅给出一堆数字而没有解释，好比只共享了加密文本而不共享解密算法，本质上不能被视为符合数据共享标准。

### 社交网络

每个人每天都会在互联网上花费时间，博客或社交网络是有机融合。课题组或个人要有自己的发声渠道，要能记录学科内的重要进展。如果个人忙不过来，可以考虑多人合作编辑或找到组织成为作者。对外进行社交可以提供跟业界联系的渠道，也可以提高自己交流与可视化的能力。互联网只关注异常、争论与胜负而不是共识，共识可以交给科普。质疑要比实际操作轻松，但谨慎介入糊涂账话题。对自己文章要按互联网信息传播速度回复或形成论文发表来回应，不回复别人质疑会影响学术声誉，但博客行文会影响别人对你的看法。线上线下要有互动，记录回顾一些学术事项，多使用图片。后期可以构建／加入在线学术社团来放大影响力并构建研究方向的趋势感。如果你有社交恐惧，那么更要灵活使用线上社交网络来弥补线下交流的缺失。

## 学术评价

学术评价通常用来考核研究人员表现。一名优秀的研究人员要在研究领域、学科与公共三个层次上都有所体现。在研究领域内，优秀课题组可连续受邀去国家级会议上做邀请报告并在综述期刊发表该领域综述或为国家级项目评审做评委。在学科内，优秀课题组可以做到在大学科综合期刊上连续发表高引用论文并为学科教材撰写章节。在公共领域上，优秀课题组的研究成果可以被新闻媒体采访并报道或为公众输出优秀科普作品并参与公民科学家或开放日活动，有一定曝光度并为科研人员设立良好的公众形象。同时做到三个层次非常难，很多业内评价可能也不考虑公共领域影响力，但第一个层次是大多数独立课题组可以企及的，第二层次相当于研究领域的破圈与综合化，认可度比较高。毕竟，学术界的竞争从经济上看是全学科对国家科研经费的蛋糕进行切割，任何形式的破圈都有助于从更大的盘子里获取资源，是被鼓励的。

当前学术评价趋于量化，常见量化指标有发表论文所在期刊的影响因子、个人的h指数及总引用数。但事实上，只要出现一个影响力评价指标，其就有可能被定向优化刷数据。预印本、开放获取期刊与社交网络互动是当前学术界的新潮流，不过也可能成为学术圈自恋的新战场，更高下载量与社交媒体转发评分（例如[altmetric](https://www.altmetric.com/) 或 [CrossRef Event Data](https://www.crossref.org/education/event-data/) ）有可能成为科研人员继SCI论文、[影响因子](https://onlinelibrary.wiley.com/doi/full/10.1111/eci.13151)与h指数后新的“优化”[指数](https://liorpachter.wordpress.com/2019/01/29/technologies-of-narcissism/)。很多技巧已经是公开的秘密，例如[提前发表可以提高影响因子](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0053374)、[题目越短引用越多](http://rsos.royalsocietypublishing.org/content/2/8/150266) 等。

定量考察会被刷数据而不定量考察则无法公平比对，目前学术评价倾向于对学术成果的质量与数量综合考察，例如最近5年的5篇代表作，或者单篇论文在综述内的正面评价等。除了成果发表数据，审稿数据与研究可重复性也可作为科研评价指标。现代科研人员应顺应趋势，早日构建在线个人档案与学术名片，用持续化、透明化、常态化心态来应对学术评价，用日常积累减少耗费在整理材料上的时间。

从评价方角度，学术研究要考虑犯错与项目失败的情况，根据实际问题来分配资源。如果奉行成功引导成功的策略，那么科研人员都会去做四平八稳的八股科研来保证产出而不是尝试开拓新领域。同样，要重视那些结果不显著的研究，如果不对这些结果汇总，那么很多资源可能要反复浪费在这些永不发表的结果上。学术评价要重视青年科研人员在团队中的作用，现在很多论文要求注明贡献，评价个人时应更多考虑贡献类型来分类评价，鼓励不同种类与不同层次的创新。

## 课题组管理

现代科研人员需要了解课题组管理方法。无规矩不成方圆，本节直接给出课题组规章与实验室规章的一个案例，然后讨论下项目管理、经费管理及心理辅导等课题组管理的重要议题。

### 课题组规章（示例）

- 指导方式与风格要尽早说明，实验室内部规定公开化、透明化，每年修订
- 课题组成员一定要经过安全培训，预留紧急联系人
- 人员管理要及时，新成员两轮面试，一轮课题组长，一轮课题组成员，两轮均通过可接纳为新成员
- 新入组成员可在课题组长处领取课题组电子资源的账号，结题后文件夹转为只读
- 课题组正式成员必须是计划在组内学习工作超过一年的成年人，能为自己行为负责
- 课题组临时成员为短期交流人员，参与组会与一对一讨论，不考核表现
- 课题组成员应遵纪守法，学术不端直接上报开除
- 课题组原则上不申报或接受涉密项目
- 日常实时交流要与生活社交工具分割
- 按项目组织交流，原则上项目两年内必须结题，不论成败均需要在课题组网站公布署名项目报告，项目报告源于项目计划，包含项目进展细节与原始数据索引，最后要有明确结论
- 分享课题组文献库
- 提倡同龄人互相指导，自主解决问题
- 定期交流，组会分为一对一讨论与集体组会，一对一讨论两周一次，原则上不超过一小时，需要交进度报告存档，仅个人与课题组长参与。集体组会一周一次，每次一个人讲项目大家讨论，可以是立项也可以是进展，一个人讲文献，然后讨论实验室内部管理问题，最后可讨论科研以外问题。每学期初定下各次组会主持人，主持人在会前一天发布集体组会内容预告，集体组会原则上不超过三小时。课题组长因故不在时，一对一组会取消但仍要提交进展报告，集体组会照常进行。课题组成员原则上不得缺席集体组会，缺席要报备主持人
- 进度报告原则上不超过一页纸，包括上次讨论问题的追踪，新发现的问题与下阶段要解决的问题，具体内容更新到到项目报告里讨论
- 仪器耗材购买需在组会上提出，课题组长判断，购买记录打印存档
- 因个人失误造成的课题组经济损失如与课题组被资助项目相关，损失由课题组承担，其他则视情况由成员与课题组共同承担
- 提倡开源项目开发，无论是否与课题相关均可作为项目成果回报，但不可作为毕业项目
- 课题组科研资源优先满足组内成员项目，其他课题组使用应报备课题组长
- 禁止组内随份子钱及其他可能造成经济压力的活动，生日节日互赠礼物实体（不提倡）涉及金额不得超过赠与人月收入1%，社会募捐赞助金额建议上限为个人月收入10%
- 了解课题组外的资源，鼓励合作
- 课题组成员可视自身情况积极申请奖项与基金，但至少要完成一个项目后才会获得课题组推荐
- 课题组正式成员应做到可随时向组外成员介绍课题组已公开的工作
- 开会学生一年一次机会，口头报告额外多一次，出国会议每个博士生有一次机会，申请到经费或自费的不算
- 每个学生每两年可申请一次付费培训，内容必须与科研项目有关
- 假期符合国家规定，除此之外工作日年假十天，提前一周报备，病假每月一天，假期当年用不完第二年折半累积
- 不提倡加班，提倡错时利用有限资源与高效学习工作
- 补助不低于学校同院系课题组中位数
- 在学期间生育不论男女不建议参与有机溶剂相关项目，可申请休学半年到一年
- 课题组成员如因故中断项目或学业，请尽早通知课题组长
- 文章挂名写清楚贡献，无贡献不挂名，合作方要求挂名请尽早通知课题组长判断
- 毕业生毕业最低标准为硕士主导完整完成一个科研项目，博士主导完成三个科研项目，每个项目长度原则上不超过两年，包括失败的项目
- 毕业生毕业答辩请认真准备，符合组内毕业标准不意味能顺利拿到学位，只说明课题组不会卡人
- 毕业生达到毕业标准后可自行决定毕业时间，提前半年通知课题组长，课题组长推荐信会公开在课题组网站备用
- 毕业生毕业前半年可不进行一对一讨论与集体组会，专心准备毕业相关事宜，如果需要实习请提前告知课题组长
- 毕业生交接请预留一个月时间，所有实验原始记录要完整可追踪，附有电子版或电子版摘要
- 规章最终解释权归课题组长

### 实验室规章（示例）

- 有害化学品包括腐蚀性的（corrosive）、急性毒性的（acutely toxic）、可燃性的（flammable）、氧化物（oxidizer/reactive）、爆炸性的（explosive）、有害健康的（health hazard）、压缩气体（compressed gas）、刺激性的（warning/irritant）、有害环境的（environmental hazard），研究人员要熟悉不同有害化学品的[标记](https://i.loli.net/2020/10/03/2e1CVSz9OIDpoc5.png)
- 使用化学品要贴[标签](https://i.loli.net/2020/10/03/2e1CVSz9OIDpoc5.png)，购买的药品会有厂家标注，但自己转移到其他容器的药品要自己标注，至少包括名称、危险性、CAS#、过期日期。
- 化学品要登记到实验室备查，注明名称、储存位置、过期日期、危险性等信息，危险性高的药品要对每次使用进行登记，记录使用量
- 所有化学品要包括纸质版安全数据表（safety data sheets），集中放在一处方便随时查询，此表可从生产商或网上找到。
- 如察觉到化学品泄漏请视情况做紧急处理，然后上报药品管理部门备案。
- 化学品暴露途径包括吸入（inhalation）、摄入（ingestion）、吸收（absorption）、注射（injection）
- 实验室要保证通风、卫生、规范操作、提供个人防护品与安全训练
- 个人责任要理解研究用化学品的危害、知道安全数据表在哪、接受训练、遵守操作规范、使用个人防护品并汇报化学品泄漏事故
- 课题组长责任要与组员讨论安全问题、提供培训、提供标准操作流程、提供个人防护品并汇报化学品泄漏事故
- 药品管理部门要定期巡检、消除各类安全隐患、提供培训并处理化学品泄漏事故
- 实验室废弃物要进行标注，至少包括名字（全称，不可缩写）、危害、“危险废物”的标识、课题组、储存位置与联系方式
- 实验室要规划出固定区域存储危险废物，容器要与危险废物组分相容
- 玻璃锐器相关危险废物要单独存放、生物制品相关危险废物要单独存放、日常垃圾要与实验室危险废物分开存放
- 明确紧急联系人，第一紧急联系人是课题组长，之后是安全部门，然后是警察或消防局，对于特定化学品，使用者知道的比其他人要多，采用传统应对方式可能引发更重危机
- 个人防护品至少包括防护镜、面罩、工作鞋、工作服与手套，必要时考虑头盔、耳罩，普通眼镜不能替代防护镜，进实验室必须穿工作服，分析实验室工作人员内禁止使用含强散发性气味的个人护理品与金属配饰

### 项目管理

科研项目的日常管理的原则可以有效提高工作效率，这部分内容即使离开学术界也对后续从事其他工作有帮助。虽然会涉及很多技巧，但技巧只是程序上简化思考的一种方式，沉溺于技术细节与选择不会真正提升效率，更重要的是打磨出适合自己可长期坚持的工作习惯。

想开展项目，搞清楚研究目的，项目的进行一定是推动个人或课题组成长的，与目的违背的项目源头上否定。要先对自己跟同行有清晰的了解，知道优势跟局限性。这里推荐 [SWOT分析](https://zh.wikipedia.org/wiki/%E5%BC%B7%E5%BC%B1%E5%8D%B1%E6%A9%9F%E5%88%86%E6%9E%90)：先列举自己技术的优势与劣势，再列举外部环境的机会与威胁，对内外进行组合，设置对策，优势机会要扩张，劣势机会要补充不足，优势威胁要有预案，劣势威胁要对冲风险。

每一个项目事先要进行规划。项目规划期间要发挥团队作用，进行内部头脑风暴，每个人都提出跟主题相关的内容，做成思维导图。然后对事项按工作量与影响力进行区分，选取工作量低但影响力大的方案。计划的目的是了解情况而不是制定教条，要预留结果不理想后的其他方案或灵活度。然后分拆出具体有时间期限的可执行的步骤，时间安排上可根据[紧急重要四象限](https://wiki.mbalib.com/wiki/%E6%97%B6%E9%97%B4%E2%80%9C%E5%9B%9B%E8%B1%A1%E9%99%90%E2%80%9D%E6%B3%95)来设计，优化步骤让所有事都在重要但不紧急的阶段完成。然后对项目的安全与经济风险进行列表，设计紧急预案，做到执行成本可控。

实际科研并不是围绕单一项目，每个个体会有自己主导的课题，也会参与其他人的项目或同时主导多个课题。此时要做好整体时间安排，利用不同研究项目切换来转移压力放松，保证时间都浪费在有意义的事上，这里可以使用[甘特图](https://zh.wikipedia.org/wiki/%E7%94%98%E7%89%B9%E5%9B%BE)来做时间规划。以项目为中心的管理是不同于被安排分工的传统模式的，需要扁平化管理，每个项目立项后有独立责任人与分工，项目完成则解散项目组。团队超过10人就要分拆，项目由需求与进展来指定或轮转个体角色，更好锻炼团队每个成员的综合能力，也避免个体螺丝钉化。

项目执行中最大问题是拖延症，此时可参照计划中分拆出具体可执行的步骤来按部就班，执行时不思考整体，关注当下并进行记录，分阶段有始有终，每一阶段要停一下或定期整理记录并思考过程中出得问题与解决方案。如果对后续执行作出修改，一定知会所有团队相关成员。拖延症本质上是跟未来的自己博弈，如果自己对自控力没信心，可以尝试软件开发中的[向后工作法](https://www.allthingsdistributed.com/2006/11/working_backwards.html) ：先公开新闻稿，写问答，写用户文档，最后去写代码。在向后工作法中，你会受到来自外界的监督压力，也会在项目开始阶段就考虑审稿人或同行的批评，这样执行时目的更明确。项目进行中遇到新知识或者请教懂得人，或者自学，不要不停犹豫不前，随时把执行放在第一位。如果需要自学，推荐- [康奈尔笔记法](https://zh.wikipedia.org/wiki/%E5%BA%B7%E5%A5%88%E5%B0%94%E7%AC%94%E8%AE%B0%E6%B3%95)与费曼学习法。前者强调回顾，后者强调通过教或写文章总结来学，一般人对新知识自己理解要求低于对他人输出知识的要求，当你需要教别人或公开自己的学习笔记时，会更严谨对待，也是跟自己惰性的博弈。

项目完成后要对项目进行回顾并整理成报告存档。项目计划就是项目报告的前身与扩展，做好文档的版本管理即可。项目计划的步骤与实际步骤没必要一一对应但要有记录，报告要附带对原始记录的索引或直接将原始记录贴上去，所有针对项目的讨论与进展都要体现在报告里。报告可以同时附带更新幻灯片版，在拿到数据的同时做出发表质量的图像，如果需要对外报告可以在半小时内拿出成品。最终报告除了结果也要总结过程得失，特别是对比实际过程与计划步骤的差距，进而优化下一个项目的计划。

这是项目报告模版：

- 题目/开题时间/项目参与人
- 研究目的
- SWOT分析
- 团队头脑风暴脑图与预案分析
- 可执行步骤的时间规划
- 风险预案
- 实际步骤记录与分阶段总结
- 结果与讨论
- 结论
- 得失与下一步计划
- 附录

### 经费管理

课题组运转需要经费，经费来源主要是分为纵向课题与横向课题。纵向课题经费一般指来自国家财政拨款的经费，如果课题组依赖平台，经费可能是直接划拨，否则是由课题组成员以个人或合作者名义向国家自然科学基金委、教育部、科技部等国家级单位或省市级单位申请获批的。横向课题经费则是课题组通过依托单位或自己从政府以外的机构获得的资金，可能来自企业，也可能来自于非盈利机构。按经费性质可以分为支持个人的与支持项目的，前者使用比较灵活，经常与奖项荣誉挂钩，后者则专款专用，事实上支持个人的经费通常也会限制在科研用途。

对于个人而言，成立课题组时所在单位应配置一定启动资金用来开展科研工作。之后可以阶梯申请国自然、面上、重大项目等以项目为中心的基金，也可以走个人属性比较重的青千、优青、杰青、长江学者等的申请。个人可以作为项目负责人，也可以仅仅就是以合作形式来获取运行经费。要合理根据申请限制来规划申请进度，防止出现经费断档的尴尬。

课题组应根据规模要研究需求来使用人力资源。课题组规模在十人以下时，大概会有一多半不同年级的硕士博士研究生外加一到两名博后与一到两名研究助理或实验室管理员，每年完成成果不少于三项，此时课题组长可借助院系实验室平台来管理课题组行政事物。当课题组规模超过十人，应配专门科研助理或进行课题组分拆，应尽量保持管理扁平化规避层级管理中信息交流不畅的问题。此外课题组可能要负担组内成员的工资，理工科运行经费要在百万人民币量级，而经费中大概两成可以用来作为工资或劳务费且都需要按预算执行，另外院系平台也会按比例向获批经费收取管理费来运行辅助科研的行政、后勤等支撑部门，实验室与办公室也会收取租金与水电费。

基金申请不可使用已经完成的结果，但可提供部分预实验结果来进行支持。要提供摘要、参与者、预算信息，重点给出立项依据、研究内容及关键科学问题、可行性分析，要提供项目特色与创新点并给出时间表。此外，基金申请通常也需要提供研究基础与工作条件方便评审者评估。

基金申请一定要事先看好关键时间节点与年龄节点，评审结果通常有评分，评分超过一定标准才能进入进一步筛选，认真阅读评审意见但没必要完全迎合评审人兴趣。项目获批后一般都需要中期进度报告与结题报告。所有报告都要存档并能追踪到撰写者与原始[数据](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002333)。另外基金申请如果要求在发表论文中注明，请仔细核对申请号。

### 心理辅导

课题组长或研究生导师应重视自己与研究生的心理辅导，学校与机构应提供免费或补贴的心理咨询。研究工作极大概率会遭遇不顺，伴随的心理压力会很大，负面情绪要学会自我及时疏导与排解，不要排斥寻求外部帮助。

对于课题组长或研究生导师，外部压力来源主要是课题组运行经费筹集与学术荣誉评比。课题组规模要提前根据经费规划，不要盲目扩张或收缩。学术荣誉其实是别人说了算，重在参与，是非功过让时间来说话。研究上的不顺利可以通过教学来互补，正确评估自己的实力，可以激流勇进，也学会激流勇退，为后来者铺路。同时，当研究生目的不在科研时，可以沟通协商后制定退出策略，不要把自己的压力过多转嫁给学生。当学生比较脆弱无法承受项目失败时，要及时中止或暂停项目，预防极端现象。

对于研究生，在读期间会有来自家庭、男女朋友、导师、同龄人的各种压力。因为时代在变，导师、父母还有亲友不一定能理解你，同龄人能理解但可能不但没有解决方案反而给你更多压力。不过，请理解导师与父母会经历你也无法理解的他们成长年代的艰辛，他们看你们总会觉得你们条件比他们好很多，这些都是正常的，人与人间互相理解是小概率事件，所以我们才通过制度与标准降低理解门槛，但这些很难照顾到当时感受。当你被压力折磨时，可以通过发展个人兴趣爱好来转移注意力，但真正能消解压力的还是对未来的信心。读研走科研这条路对于一大半的人而言是死胡同，现有资源无法保证舒舒服服做科研但不用承担失败责任，因此肄业或拿到学位转行是常态，及时跟导师或更高层管理者沟通。要理解导师不见得是心理健康的人，沟通无效可选择转导师。

总之，没有人是天生的抗压者，也不存在零风险的科研，及时的心理辅导对于导师与研究生都很重要。在制度平台不够完美时，请构建不影响别人与伤害自己的自我疏导方式。

## 讲课

现代科研人员所在的研究机构通常会承担教学任务，本节会重点讨论讲课相关的注意事项。

### 学生如何学习？

首先搞清楚你自己学科里学习的含义，如何去掌握知识，自己在学习过程中有益的经验。学生的学习方法有深入学习、策略学习还有表面学习。了解个体学习的差异如何影响学习效果，例如前置知识、动机、学习策略还有对于学习智力能力的信仰。掌握元认知方法，掌控自己的思考过程。明白教学是承前启后的受多方面影响，要根据内容与学生调节教学方法，要知道学生对不同教学环境的应对策略。

### 如何激励学生？

激励就是让学生渴望或乐意做某事。激励的理论模型：

- 期望-价值理论：学生对目标有一个期望并对这个期望有一个价值判断
- 成就目标导向理论：有些人是掌握目标导向，有些是表现目标导向
- 成长-固定思维模式：有些人认为能力可以不断发展，有些则认为无法变化
- 自我表现理论：人类三个基本需求：能力认可、归属感及自治
激励方法就是让学生提高激励的体验，例如预先教一些技术提高完成度、课前测试、让学生选择主题、分享学习经验、提供正面反馈、考核时比较灵活（6次作业取5次成绩）

在教学时要考虑作业与评价方式、学习活动、反馈还有课堂气氛。给予学生主动权，提高存在感与社交活跃度，建立对教学行为评价的持续反馈机制，记住学生的名字...

### 评价学习

学习金字塔从下往上：记忆-理解-应用-分析-评价-创造，可参照设计不同难度的考核。学生学什么与怎么学经常依赖于如何被评价，评价有三种形式：

- 诊断式：小测试、涂鸦板、头脑风暴、一对一会议、思维导图还有概念测试
- 形成性：让学生提出最难懂的问题、一分钟论文、小抄、随堂测试（给出比例）、同行评议、反馈、问题集、非正式展示、进展报告
- 总结性：期中期末最终展示

教学目标、教学行为与反馈之间要相互有联系，给出指引，自己先完成并且对学生作业做出点评。

### 课程设计

从教学目标、教学形式和评价三个方面入手考虑课程设计。首先整理课程概念，头脑风暴选出来以后思考概念间的联系，反复思考概念间的相互关系。课程结束后可以让学生自己去绘制自己的课程地图。教学目标上从学生角度出发，考虑他们通过课程知道什么、做什么以及有什么样的感受，就是从脑、心、手三个方面去设立，用强动词例如解决、设计、定义、评价而不要用知道、理解等词来设立目标。评价方法参考上面评价章节。教学形式上明确学习时间不同于上课时间，提供知识与实践反馈，采取主动教学等策略，可参考布鲁姆分类学，另外教案与视频要做到在线化。

### 互动学习

互动学习是提高课堂参与度的组织形式，例如分组相互讨论。课程设计可以按照预热-小教程-团体活动-分享来划分时间。翻转课堂也可以作为一种互动学习的手段来尝试。

### 教学理念

教学理念是教学档案的一部分，常用来作为简历教学经历的补充。一般一页，列举三个教学理念。整理教学理念常用来整理自己关于教学的理解，作为教学的行动指南，也可以用到教育相关工作申请上。首先去思考理念的来源与如何起源，然后可以采用隐喻来阐述教育理念，例如园丁、教练、瑞士军刀等。

这里简单介绍下常见的教学理念：从已知到未知，也就是在教授任何新东西前先要介绍原来就有或者之前教过的概念，然后从已知概念存在的问题入手，揭示新概念的必要性，打个比方，想讲解持久性有机污染物这个概念可以先从DDT农药这一相对简单的概念开始讲，然后过渡到存在类似问题的其他污染物，最后自然引导出持久性有机污染物的概念；费曼学习法，就是鼓励学生以教代学，把自己刚学会的东西教给另一个同学，当另一个同学提出问题时去反思自己的理解哪里有问题，然后不断加深理解，相当于通过反馈来提高理解力；与费曼学习法类似的一种教学理念是苏格拉底式提问，通过不断的向学生质疑促进学生的思辨能力，当然这个方法用得好学生受益匪浅，用不好杀人诛心。
