# 就业{#career}

在第二章中我们提到了博士存在的就业问题，就结果而言，博士在博士阶段结束后选择博士后更多是为了下一人生阶段的就业制造机会，而就业不仅仅只是学术界。本章将重点讨论就业相关议题。求职过程一般包括投简历、搭人脉、面试、获得职位、事业发展等流程。

## 商业与学术

商业的两条规则：营利与持续改进，所有的招聘信息会根据这两条规则来设计。学术界与之对应的则是成果发表与持续改进。其实商业与学术界都有周期性，在学术界，你的周期是：

- 提出假设
- 设计与实验
- 成果发表
- 改进或提出下一个假设

而商业周期则是：

- 提出目标
- 执行或生产
- 市场检验
- 调整或提出下一个目标

你会发现这两个并不矛盾，技能要求也类似，你所需要的是把学术用语转为商业用语。而商业所需要的技能集主要包括创新与风险管理、生产力改进、执行控制与财务规划。

同时有些技能在学术界与商界是通用的，那就是团队管理与交流等社交技能。当你具备这些技能后，进行职业转换其实就是换一套术语体系讲故事。有些主题例如项目管理与时间管理等内容前面章节已经叙述可自行对应。

## 简历

cv 是完整的个人信息，resume一般1-2页，结果导向。招聘中一般只用resume而cv一般是存档或背景检查用的。resume会包含个人陈述部分而cv更多是事实罗列。你需要日常维护cv，求职时则要根据招聘信息对cv进行优化。有两点要注意：对外对内要用不同邮箱进行区分且最好有个人简短不重复的ID，这对招聘方来说比较有利。

一条招聘信息通常包含三层技能需求：科研技能要求、商业技能要求与社交技能要求。毕业生通常只会关注科研技能要求但其实科研技能要求虽然是门槛，但造成职业竞争力差异的并不是科研技能，而是商业技能与社交要求是否在简历中体现，特别是那些在招聘信息里写的很清楚的却常被忽视的。一份招聘如果标注了团队能力、项目管理就要针对性对你自己的经历进行描述。这些三层内容要在简历的个人陈述中分段体现，给招聘者的信号就是你不但读了招聘信息还读懂了企业的需求。

与简历相关的是求职信（cover letter），通常来说如果没有特别说你要提交就可以告诉招聘者简历是不是目的性的及覆盖的内容，然后就是留下联系方式。如果你有与招聘者的社交联系或正面评论等简历里不合适出现的内容可以在求职信里提，例如读过论文及会议上留意过展台，一定要诚实，不要能巧成拙！在邮件联系时要礼貌（及时发送感谢信）且及时跟进（follow up），正常人都想做个好人，特别是对弱联系或一面之缘的人。

## 人脉

简历的准备主要不是指望海投可以投中，而是在理想职位出现后通过最合适的人替你内推并拿到面试机会（占比80%）。不论职场还是学术界，人们都喜欢从了解的人那里获得推荐候选人，一方面有人背书，另一方面海投过来的信息存在大量非目的性简历而筛选简历经常是很任性的过程。你的求职目标就是找一个自己喜欢且招聘方也会对你满意的职位，不了解自己与对方需求的简历是对双方时间精力的浪费。

在于陌生人建立联系时，可通过亲朋好友或校友老乡等入手，也可以参与主题聚会并通过共同场景建立联系。不同于学术界，社会职场每个人的知识背景是不一样的，不要使用专业术语来跟非专业人士交流。一个合格博士需要有能力用通俗语言跟他人交流，特别是你的研究内容，全是专业术语更多显示的是对本质的不理解。事物可以是复杂的，但不能是说不清楚的。

在与人交流时一定要意识到每个人都是独立的个体，有自己的性格与处事方式，即使跟你不一样也不代表就更厉害或不好。这种对他人的理解首先要建立在对自己的理解上，在你眼里也许自己很完美，但在别人眼里可能存在不同解读，你可以不在乎但不能不知道这种可能性的存在。同样，对别人也不要轻易评价与人云亦云，要能体会尊重他人的独特性或制定相应高效交流方式。你建立联系的人要提供其建立联系后额外的价值或引起兴趣，如果一味放低姿态，对方可能不会尊重你。

商业培训里喜欢用MTBI测试来对职场中人格进行分类。你可以先做一套测试，然后你会得到四个字母来描述你。每个字母代表一种二分法，例如I代表内向而E代表外向，N代表直觉而S代表感觉，T代表思考而F代表情感，J代表判断而P代表感知。虽然学界对这个没有统一意见但不妨碍很多人在用这个对人进行预判与交流方式的试探，例如对于一个TJ的人随意改变计划几乎是不可接受的。

职场人对外交流有三个标签：机构、职业与个人。陌生人间的交流最好从个人经历出发而不是社会机构角色出发，后者是机械且标签化的，不利于有效沟通。对外交流要了解镜像神经元理论，也就是交流双方都会在交流中不自觉尝试模拟对方促进交流，而镜像神经元更多依赖行为与语言引导。一个常见的技巧就是专家到学习者的角色转换，当别人问你问题时，不要着急堆砌专业词汇，而可以反问对方问题来切换为学习者角色来更多了解事实并最终提供其原始问题的答案。

具体训练交际技能可参考3M&M方法。当A问B一个问题时，B反问A三个问题，问问题前吃一颗糖豆来给自己思考时间，得到答案后再回答A最初问题，提问过程中要注意对方性格类型与情感诉求，然后用个人角色出发在理解同情角度解决或回答对方提出的问题。另一种练习的方式叫做 elevator pitch，也就是模拟两个人在电梯里偶遇然后用大概1-3分钟时间把你想说的事说清楚。

在建立了有效的联系后，你需要一定的维护，可以通过邮件往来或社交网络关注。注意，你不需要很密切的联系而是更多让对方对你有一个角色标签，这样对方遇到合适职位时会联想到你。而另一种联系方式就是信息面试（ information interview），当你特别想取得一个职位时，需要通过人脉来非正式了解情况，此时可以约下相关人来聊天。首先你要自己进行一定调研，这样不浪费双方时间，然后准备好帮助对方想起你的自我介绍，然后对话以寻求建议与背景信息为主而非针对职位，特别是在招聘信息或官方网站上没有提及的内容，对话后发送邮件表示感谢。

## 面试

要做好充分准备，了解公司运营、财报、新闻，从社交网络里获取面试人的角色信息。要尊重面试官，眼神要直视，回答问题前要停顿一下过脑子，多听少说别打岔。回答问题可采用 STAR 方法，也就是场景（situation）- 任务（task）- 行动（action）- 结果（result）。先给出场景，然后描述你的任务，然后叙述你采取的行动并最终总结结果，要言之有物。

下面是常见的面试问题，可事先准备或练习：

- 介绍下自己
- 你的哪些科研技能符合职位要求
- 你跟其他候选人的最大区别是什么
- 举一个你提高实验室效率的例子
- 实验不成功如何处理
- 如何训练实验室新人
- 讲一个别人让你失望的例子
- 讲一下你用来保障你研究优势的策略
- 当研究中出现意外与挑战如何应对
- 描述下你当前研究的工作流程
- 你的研究专长是如何应对外部挑战的
- 你是如何帮助同事解决你专长的问题的
- 除了科研技能，你了解哪些商业技能，你是否应用过
- 描述一个外部机遇下你如何扬长避短
- 你如何利用人脉来为岗位提高生产力
- 讲一个实验室外体现你领导力的案例
- 你当前研究的商业价值是什么
- 给你1000万美金，你会投给谁
- 我们为什么要雇佣你
- 基于你的背景，我们能给出的薪水是XX，你会接受吗
- 你当前研究项目的成功标准是什么
- 你当前研究项目最贵的组成部分是什么
- 讲一个你管理时间的案例
- 你当前工作的里程碑是什么

## 职场

日常工作中要懂得向上管理，也就是合理向你的上级表述你的需求、意愿来达成你的工作目标。向上管理意味着你的角色是主动的而不是被动的，对于工作推进总是积极态度而不是一味听指挥。与上级不同意见时，要用对事不对人的态度从数据、外部环境等客观事实出发解释不同决策下会出现的不同境遇，把决策权有导向性的给上级进行传递。同时，要对上级利益关系有清楚了解，如果上级阻碍你的长期个人发展，尽早考虑下一份工作而不是长期内耗。

给同事或上下级反馈要采取绩效反馈（performance feedback）的方式来进行持续改进与量化评价管理（例如six sigma 的黑带认证）。不要泛泛而谈大道理而是专注到具体的事，不要针对个人而是针对行为表现进行反馈，目标是为了帮助而不是打击，给出的意见要具备可执行性且点到为止，要在反馈中询问对方是否听明白，然后之后要跟进结果。在发现低效行为时马上进行反馈纠正，指出期望与评价标准，阐述行为后果与高效的行为后果并鼓励改进，不要抓着一点不妨且避免公开指责，设定截止日期来检查结果，向前推进。发现高效行为时要马上嘉奖给予正反馈，也要指出你的评价标准与该行为对目标的帮助，鼓励是为了保持高水平绩效。

职场里谈判分为分配式谈判（distributive negotiation）与整合式谈判（integrative negotiation），前者是零和博弈非此即彼的谈判而后者是提供双方额外价值的双赢谈判，尽量将谈判做成整合式的而不是分配式的。职业是会换或者需要晋升的，你个人在人生不同阶段需求不一样，对应的职业需求也不一样，一般三到五年一个周期进行调整，原则上非升即走。升可以包括福利升级、工资升级、岗位升级等。在加薪谈判中要更多用数据说话并站在提供更多价值角度择时择机进行整合式谈判。但安于现状或进行工作生活平衡也是个人选择自由，请根据自身需求提出要求。另外，要了解团队加入你或不加入你的区别，这样就知道你自己对外的价值。从公司角度，他们会压低每个人的重要性而保证整体价值最大，此时他们就会出现功能冗余，大公司几乎都会过度雇佣。在一个联盟里，要知道自己的夏普利值，也就是在不同加入次序下你对团队完成任务的平均贡献。在投票中，夏普利值并不与人数对应，团体代表如果达不到一定程度，可能存在就算人数不少，但决策能力为零的情况。

职场成功要牢记这个公式：

成功=a×实力+（1-a）×运气

搞清楚自己实力与运气的比例，如果你运气很好，那么某个职位上就要虚心多去请教前辈才能更上层楼而不是感觉无所谓。运气只有在实力相当时才会起作用（实力悖论），否则德不配位就比较麻烦。

职场中的项目管理与学术项目管理类似，参考前一章内容。

## 职业

### 学科鄙视链

### 博后

欧洲

hard money soft money

企业博后

### 常任轨

- 常任轨研究教授
- 常任轨文理学院教授

### 非常任轨

- 研究性教职
- 行政工作

### 非高等教育

- k12教育

### 政府

### 科学顾问

in house

专利考试

注意细节拼写与写作

### 咨询

解决问题的方案

### 企业科研/药企

药企与医学院

### 销售与应用专家及营销

主要在仪器公司工作，为科研需求提供支持。

### 创业

### 编辑/出版社

认真严谨但更重要的是对学科前沿的把握

### NGO

主要管理基金，产学研结合。

### 金融

工作压力大，资金流全流程了解

### 公共卫生

复杂性学科

### 科学传播

把自己的成果讲给别人

### 医药交流

把科研进展带给医生（medical science liaison）
帮助药厂把新药与疗法传播给客户（medical communication）

### 数据科学家

分析数据


