# 就业{#career}

在第三章中我们提到了博士存在的就业问题，就结果而言，博士在博士阶段结束后选择博士后更多是为了下一人生阶段的就业制造机会，而就业不仅仅只是学术界。本章将重点讨论就业相关议题。求职过程一般包括投简历、搭人脉、面试、获得职位、事业发展等流程。这里还是要强调，伴随扩招与产业升级，取得博士学位后最终留在学术界的比例会越来越低，本章所讨论的问题哪怕你目前认为用不上也最好了解下。

## 商业与学术

商业的两条规则：营利与持续改进，所有的招聘信息会根据这两条规则来设计。学术界与之对应的则是成果发表与持续改进。其实商业与学术界都有周期性，在学术界，你的周期是：

- 提出假设
- 成立研究团队
- 设计实验做实验
- 成果投稿与发表
- 改进或提出下一个假设

而商业周期则是：

- 提出目标
- 成立项目组
- 执行与生产
- 市场检验与宣传
- 调整或提出下一个目标

你会发现这两个并不矛盾，技能要求也类似，你所需要的是把学术用语转为商业用语。而商业所需要的技能集主要包括创新与风险管理、生产力改进、执行控制与财务规划。

同时有些技能在学术界与商界是通用的，那就是团队管理与交流等社交技能。当你具备这些技能后，进行职业转换其实就是换一套术语体系讲故事。有些主题例如项目管理与时间管理等内容前面章节已经叙述可自行对应。

## 简历

就业的第一步永远是了解自己，尽早进行自己的个人发展规划（individual development plan，IDP）。所谓个人发展规划，就是要对自己的技能、兴趣还有价值观进行评估。所谓技能，就是你能为别人或企业提供的能力，这是招聘方视角重点关注的，要学会从别人视角给自己的能力列清单。兴趣就是你想做的事或理想的事业，这个可能与你的技能匹配或不匹配，但无论如何你得知道自己想要什么。所谓价值观，就是你工作会看重的东西，薪水、团队、安全感等都算。个人发展规划的目标就是把技能、兴趣与价值观列出来然后下阶段努力把这些对齐或调谐，以此为找工作的指导方向。只要你肯列出来，就会消除很多迷茫，有些岗位也许光鲜但不对你胃口，有些岗位短期内痛苦但可能最大限度实现你人生价值，此时有这样一个规划一对比就清楚很多了。网上也存在大量量化的个人职业测评之类的产品，但本质就是要在找工作前充分理解自己对别人的价值及自己想要的价值。

投简历要搞清楚cv跟resume这两个概念，cv 是完整的个人信息，resume一般1-2页，结果导向或者是根据不同职位打造不同 resume 而不是一个文本走天下。招聘中一般只用resume而cv一般是存档或背景检查用的。resume会包含个人陈述部分而cv更多是事实罗列，个人陈述部分一定是要与招聘信息有呼应，符合的条件要多说但不具备的别瞎说。你需要日常维护cv，求职时则要根据招聘信息对cv进行优化。一份简历至少要包括个人联系信息、教育经历、工作经历与成果。有两点要注意：对外对内要用不同邮箱进行区分且最好有个人简短不重复的ID，这对招聘方来说比较有利。

一条招聘信息通常包含三层技能需求：科研技能要求、商业技能要求与社交技能要求。毕业生通常只会关注科研技能要求但其实科研技能要求虽然是门槛，但造成职业竞争力差异的并不是科研技能，而是商业技能与社交要求是否在简历中体现，特别是那些在招聘信息里写的很清楚的却常被忽视的。一份招聘如果标注了团队能力、项目管理就要针对性对你自己的经历进行描述。这些三层内容要在简历的个人陈述中分段体现，给招聘者的信号就是你不但读了招聘信息还读懂了企业的需求。

与简历相关的是求职信（cover letter），通常来说如果没有特别说你要提交就可以告诉招聘者简历是不是目的性的及覆盖的内容，然后就是留下联系方式，简明扼要不要重复简历内容。如果你有与招聘者的社交联系或正面评论等简历里不合适出现的内容可以在求职信里提，例如读过论文及会议上留意过展台，一定要诚实，很多东西大家都懂但不同的表述方式会产生不同效果，这也是你对外交流能力的体现。在邮件联系时要礼貌（及时发送感谢信）且及时跟进（follow up），正常人都想做个好人，特别是对弱联系或一面之缘的人。

## 人脉

简历的准备主要不是指望海投可以投中，而是在理想职位出现后通过最合适的人替你内推并拿到面试机会（占比80%）。不论职场还是学术界，人们都喜欢从了解的人那里获得推荐候选人，一方面有人背书，另一方面海投过来的信息存在大量非目的性简历而筛选简历经常是很任性的过程。你的求职目标就是找一个自己喜欢且招聘方也会对你满意的职位，不了解自己与对方需求的简历是对双方时间精力的浪费。

在于陌生人建立联系时，可通过亲朋好友或校友老乡等入手，也可以参与主题聚会并通过共同场景建立联系。不同于学术界，社会职场每个人的知识背景是不一样的，不要使用专业术语来跟非专业人士交流。一个合格博士需要有能力用通俗语言跟他人交流，特别是你的研究内容，全是专业术语更多显示的是对本质的不理解。事物可以是复杂的，但不能是说不清楚的。

在与人交流时一定要意识到每个人都是独立的个体，有自己的性格与处事方式，即使跟你不一样也不代表就更厉害或不好。这种对他人的理解首先要建立在对自己的理解上，在你眼里也许自己很完美，但在别人眼里可能存在不同解读，你可以不在乎但不能不知道这种可能性的存在。同样，对别人也不要轻易评价与人云亦云，要能体会尊重他人的独特性或制定相应高效交流方式。你建立联系的人要提供其建立联系后额外的价值或引起兴趣，如果一味放低姿态，对方可能不会尊重你。

商业培训里喜欢用MTBI测试来对职场中人格进行分类。你可以先做一套测试，然后你会得到四个字母来描述你。每个字母代表一种二分法，例如I代表内向而E代表外向，N代表直觉而S代表感觉，T代表思考而F代表情感，J代表判断而P代表感知。虽然学界对这个没有统一意见但不妨碍很多人在用这个对人进行预判与交流方式的试探，例如对于一个TJ的人随意改变计划几乎是不可接受的。

职场人对外交流有三个标签：机构、职业与个人。陌生人间的交流最好从个人经历出发而不是社会机构角色出发，后者是机械且标签化的，不利于有效沟通。对外交流要了解镜像神经元理论，也就是交流双方都会在交流中不自觉尝试模拟对方促进交流，而镜像神经元更多依赖行为与语言引导。一个常见的技巧就是专家到学习者的角色转换，当别人问你问题时，不要着急堆砌专业词汇，而可以反问对方问题来切换为学习者角色来更多了解事实并最终提供其原始问题的答案。

具体训练交际技能可参考3M&M方法。当A问B一个问题时，B反问A三个问题，问问题前吃一颗糖豆来给自己思考时间而不是用本能去情绪化回答问题，得到答案后再回答A最初问题，提问过程中要注意对方性格类型与情感诉求，然后用个人角色出发在理解同情角度解决或回答对方提出的问题。另一种练习的方式就是准备电梯报告，请参考前一章相关内容。

在建立了有效的联系后，你需要一定的维护，可以通过邮件往来或社交网络关注。注意，你不需要很密切的联系而是更多让对方对你有一个角色标签，这样对方遇到合适职位时会联想到你。而另一种联系方式就是信息面试（ information interview），当你特别想取得一个职位时，需要通过人脉来非正式了解情况，此时可以约下相关人来聊天。首先你要自己进行一定调研，这样不浪费双方时间，然后准备好帮助对方想起你的自我介绍，然后对话以寻求建议与背景信息为主而非针对职位，可以涉及对方的背景、日常工作及其建议，特别是在招聘信息或官方网站上没有提及的内容，对话后发送邮件表示感谢。

## 面试

要做好充分准备，了解公司运营、财报、新闻，从社交网络里获取面试人的角色信息。要尊重面试官，眼神要直视，回答问题前要停顿一下过脑子，多听少说别打岔。回答问题可采用 STAR 方法，也就是场景（situation）- 任务（task）- 行动（action）- 结果（result）。先给出场景，然后描述你的任务，然后叙述你采取的行动并最终总结结果，要言之有物。

下面是常见的面试问题，可事先准备或练习：

- 介绍下自己
- 你的哪些科研技能符合职位要求
- 你跟其他候选人的最大区别是什么
- 举一个你提高实验室效率的例子
- 实验不成功如何处理
- 如何训练实验室新人
- 讲一个别人让你失望的例子
- 讲一下你用来保障你研究优势的策略
- 当研究中出现意外与挑战如何应对
- 描述下你当前研究的工作流程
- 你的研究专长是如何应对外部挑战的
- 你是如何帮助同事解决你专长的问题的
- 除了科研技能，你了解哪些商业技能，你是否应用过
- 描述一个外部机遇下你如何扬长避短
- 你如何利用人脉来为岗位提高生产力
- 讲一个实验室外体现你领导力的案例
- 你当前研究的商业价值是什么
- 给你1000万美金，你会投给谁
- 我们为什么要雇佣你
- 基于你的背景，我们能给出的薪水是XX，你会接受吗
- 你当前研究项目的成功标准是什么
- 你当前研究项目最贵的组成部分是什么
- 讲一个你管理时间的案例
- 你当前工作的里程碑是什么

从面试官角度，他们会重点关注回答的内容是否容易理解，是否完整且会记录时间，不同面试官打分的项目不同，他们会根据结果整体去考察候选人，直接拍板的招聘要警惕。

## 职场

日常工作中要懂得向上管理，也就是合理向你的上级表述你的需求、意愿来达成你的工作目标。向上管理意味着你的角色是主动的而不是被动的，对于工作推进总是积极态度而不是一味听指挥。与上级不同意见时，要用对事不对人的态度从数据、外部环境等客观事实出发解释不同决策下会出现的不同境遇，把决策权有导向性的给上级进行传递。同时，要对上级利益关系有清楚了解，如果上级阻碍你的长期个人发展，尽早考虑下一份工作而不是长期内耗。

给同事或上下级反馈要采取绩效反馈（performance feedback）的方式来进行持续改进与量化评价管理（例如six sigma 的黑带认证）。不要泛泛而谈大道理而是专注到具体的事，不要针对个人而是针对行为表现进行反馈，目标是为了帮助而不是打击，给出的意见要具备可执行性且点到为止，要在反馈中询问对方是否听明白，然后之后要跟进结果。在发现低效行为时马上进行反馈纠正，指出期望与评价标准，阐述行为后果与高效的行为后果并鼓励改进，不要抓着一点不妨且避免公开指责，设定截止日期来检查结果，向前推进。发现高效行为时要马上嘉奖给予正反馈，也要指出你的评价标准与该行为对目标的帮助，鼓励是为了保持高水平绩效。

职场里谈判分为分配式谈判（distributive negotiation）与整合式谈判（integrative negotiation），前者是零和博弈非此即彼的谈判而后者是提供双方额外价值的双赢谈判，尽量将谈判做成整合式的而不是分配式的。职业是会换或者需要晋升的，你个人在人生不同阶段需求不一样，对应的职业需求也不一样，一般三到五年一个周期进行调整，原则上非升即走。升可以包括福利升级、工资升级、岗位升级等。在加薪谈判中要更多用数据说话并站在提供更多价值角度择时择机进行整合式谈判。但安于现状或进行工作生活平衡也是个人选择自由，请根据自身需求提出要求。另外，要了解团队加入你或不加入你的区别，这样就知道你自己对外的价值。从公司角度，他们会压低每个人的重要性而保证整体价值最大，此时他们就会出现功能冗余，大公司几乎都会过度雇佣。在一个联盟里，要知道自己的夏普利值，也就是在不同加入次序下你对团队完成任务的平均贡献。在投票中，夏普利值并不与人数对应，团体代表如果达不到一定程度，可能存在就算人数不少，但决策能力为零的情况。

职场成功要牢记这个公式：

$$成功=a×实力+（1-a）×运气$$

搞清楚自己实力与运气的比例，如果你运气很好，那么某个职位上就要虚心多去请教前辈才能更上层楼而不是感觉无所谓。运气只有在实力相当时才会起作用（实力悖论），否则德不配位就比较麻烦。

职场也需要成长，很多公司意识到员工的成长可能带来更高的回报后会持续请人来进行培训。培训的内容可能是新的技术，也可能是新的理念，公司会为员工进修报销，有的连读学位的钱都能出了。如果你所在公司提供进修的福利，一定不要浪费，现代社会每个人的成长都是贯穿终生的。

职场中的项目管理与学术项目管理类似，参考前一章内容。

## 职业

下面列举一些博士的就业方向，仅供参考。

### 博后

欧洲有玛丽居里博后与洪堡学者，日本有学术振兴会（JSPS），美国国立卫生研究院有 T32 与 K99 博后。博后要搞清楚经费来源是软钱（soft money）还是硬钱（hard money）。前者 是教授申请项目中用来支持博后的经费，一旦用光了位置就没了。后者是学校从学生学费或研究机构募集后分给课题组用来研究的经费，用光风险比较小。博后自己申到软钱可摆脱课题组对课题限制。企业博后则有较高收入且与业界结合紧密，但转回学术界会略有困难。

博后是学术界犯错有人兜底的最后一站，如果不出结果可以选择退出学术界，毕竟现在的博士毕业人数根本不可能都在学术界内消化掉。说白了博后是就业前的临时身份，所有博后阶段都要围绕就业规划。如果把博后当成推迟接触社会的避风港保持象牙塔的生存状态，就业所需要的能力得不到提高，那么很难成为学术界的独立研究人员，更不用提转行跨界所需要的能力了。

### 常任轨

常任轨包括研究教授与文理学院教授，目前国内多采用非升即走与稳定事业编两套体系，对自己实力有信心就去选非升即走。在没拿到终身教职之前，常任轨教职可能被看作高阶版博后，因为相对独立，所以会有经费压力，但如果连独立课题组都没有，那么可直接认为就是博后加长版。这一阶段需要给自己在学术界内建立影响力，同时可能也要承担教学任务。拿到终身教职最大的压力就是经费，大量的时间要放在找合作关系与经费申请上，此时要兼顾研究者与课题组管理者身份。

### 非常任轨

研究性教职或偏行政工作，这样的岗位适合只看重老师身份的人去做，通常你的经费来源由课题组长或研究所来兜底。不过非常任轨的职位很难做到完全独立，经费与研究方向跟着项目走，不过相对压力也小。偏行政方面有一类属于科研项目经理，主要负责对接基金申请与技术转化的事。这类职位需要有一定科研背景或学历要求但不需要你去做科研。

对于研究机构而言，常任轨教职是精英化的，很难维持一个很大的体量。现在越来越多的机构设立非常任轨教职来吸纳高学历研究人员做项目或辅助，很多职位其实是给过了年龄的博后准备的，因为确实存在很多研究人员既不想转行也无法长期保持博后身份做想做的研究。伴随学历通胀，这类职位可能在未来变得更普遍。

### 非高等教育

k12教育，教育研究为主，更多人选这个是为了下一代。给小学中学生当老师是很多博士的最终选择，在他们看来降维就业是平衡工作生活的最佳选择。不得不承认的是k12教育在现代社会里确实属于高投入高产出的行业，家长对这一阶段孩子的成绩期望也确实能从高投入里看到成果，对于学校而言就意味着招募高学历教师。相比之下，研究工作则会遇到高投入零产出的问题。因此，k12教育中高学历从业者可以拿到稳定的收入与较高的社会地位，然后把自己的应试技巧传承下去。想从事这个行业，最好去拿个教育硕士或者提早去考教师资格证，否则后面事业发展受限制。

### 科学顾问

律所、金融行业需要，注意细节拼写与写作，国内虽不常见但会越来越重要，也是科研人员转金融法律专业人士的重要途径。其中，最常见的高学历科学顾问一般是帮忙来审核专利的，要通过专利方面的考试。金融律所行业之所以雇佣科学顾问，一定是他们带来的收益远高于付给他们的工资。很多科学顾问在很多收购并购案、团体诉讼还有知识产权纠纷中会起到特别关键的作用，如果你的竞争对手或诉讼对手没有科学顾问，那么相同的证据摆出来解读的结果可能完全不同，这也是从事科学顾问行业的人很多最后都做到了合伙人级别的职位的原因。在律所与金融行业里，知识不仅仅是力量，还可以转化为财富。

### 科学传播

把自己的成果讲给别人或把别人的成果通俗讲给大众，需要写作技巧的专门训练。需要的知识大部分内容与前一章类似，不同的在于要针对不同媒体掌握不同交流方式，例如视频跟音频的展示策略，自己演讲还是一问一答等。要始终遵守从已知到未知、从结果到原因、从简单到复杂的讨论模式，否则观众或读者会跟不上你的思路或失去兴趣。公众喜欢听故事但很多科学问题可能有头无尾，此时也要会一些开放式结局的结体手法。学会用网络流行语、形象化语言与多媒体方式来跟无背景知识的人交流但要保持严谨，千万不要堆砌专业术语，这样不但不利于科学传播，反而会加剧科学宗教化的印象。

另外科学传播会更侧重对读者需求与认知水平的尊重，不能动不动就说某某是众所周知的。受众越广，就一定会出现嫌弃讲的过于简单或专业的评论，你只需要为大多数观众或读者负责就可以了。一定要事先了解观众或读者的基本情况，然后去调整内容，可以在报告开始阶段做二维码调查来引起观众兴趣并掌握一些基本情况。提问阶段有人偷换概念过度延伸也是正常的，此时要学会聚焦主题。另外最好事先准备一些常见问题的答案放到报告小册子里防止时间不够用。要学会时刻表示友好而不是跟审稿人一样刻薄，读者或观众带着兴趣来最好带着知识而不是负面情绪走，这就完全不利于科学传播了。

现在国内常见的科学传播职业基本都在自媒体，有些是学术机构的科学传播部门建立的，也有传统媒体转行过来的。只要内容足够优质且对写作有兴趣，借助互联网订阅、线下活动、图书出版等方式都能获得不错的薪资。

### 政府公务员

选调生或定向培养是研究生及以上从政人员的职业途径，但走得高就要放的深，从基层才能累积最务实的经验。博士从政现在不算新闻了，学者型官员目前也比较流行，当然这说的是两回事。博士从政指的是博士毕业就去地方任职这类，一般得是名校选调生才行。博士从政属于典型起点高经验少的公务员，如果没有政绩，很可能就业即巅峰。学者型官员是指在研究机构内走行政路线，一般得到学院院长或副校长这个级别才有可能被调入政府行政部门做官。学者型官员通常需要有政府机关借调或者社会兼职的经历，如果学术水平也不错，那么可能一步就从学术机构管理层转到国家部委等实权单位任职，或者通过智库顾问的方式参与政策制定。想做好公务员，一定要有足够的基层经验、很强的办事能力及社交能力。一路读到博士然后跑去从政的人志向都不可小觑。

### 非营利组织与基金会

很多博士就业最终会选择非营利组织或一些私人慈善基金来工作，薪酬上可能会比较低。选这类工作一般是打算追求个人理想的，但这些机构的运行却不是理想化而是现代化的。非营利组织也会有研究机构、需要人来管理基金、协调学术界与业界。很多你在高校或研究机构能见到的职位在非营利组织与基金会里也有。从事这类行业，有热情是起点，关键还是领导组织能力与筹款能力，是人际关系的缝合怪。

很多非营利组织有智库的职能，经常会公布一些报告，资金来源可能是民间筹集或政府。国内智库多多少少有点政府背景，很多是从原来政府机关的政策研究室一类的地方剥离出来的，另外一些则直接可以看成研究所或大学附属机构。智库有时候也是学者转官员或者商人转官员的一个身份过度机构。不过博士就业进入智库的相对比较少，智库对于经验的要求多过对学位的要求而且薪资一般。如果你打算搞清楚政策是怎么制定的，那么可以去智库体验一下，否则可以等你有想法转换职业的时候再考虑不迟。

### 编辑/出版社

认真严谨但更重要的是对学科前沿的把握，目前学术期刊倾向于雇佣职业编辑处理稿件及推广，所以要懂点现代社交网络及传播学。当前伴随开放获取的流行与大出版集团对优质稿件的竞争，很多的期刊编辑逐渐从学术兼职的专家教授转为专职人员。专职编辑人员一般都有博士学位或博士后工作经历但并不要求很高的学术水平，出版集团雇佣专职编辑主要是为了加快稿件处理速度并且应对科研领域的一些新生事物，例如预印本还有自媒体等，这些编辑通常会比较年轻且乐于接受新概念。供职于出版集团或学术期刊的专职编辑工作时间、地点都比较自由，大部分工作都可以通过互联网完成。此外，专职编辑是需要给出版集团带来利润或影响力的，很多出版集团看到了文稿润色、内部期刊转投、封面设计等业务的利润与影响力，专职编辑可根据具体情况推荐内部业务来服务读者与作者。

### 应用专家及销售

主要在科研仪器公司工作，为科研需求提供支持。这类工作一般是从应用工程师开始做，累积足够经验后转销售卖产品。应用工程师的工资是稳定的但相比销售低不少，销售主要收入是订单的提成，因为科研用仪器通常几十上百万，所以经常一年下来就需要跑几个大订单就能完成全年绩效。很多做应用转销售是看重了工作时间灵活自由，收入凭本事赚的特性。但不论应用专家还是销售，每年都需要经常出差，要么是拜访客户，要么是参与企业赞助的学术会议。想从事这个行业，最主要是保持跟之前实验室成员的联系，他们都属于潜在客户。如果做耗材，很多时候吃定几个实验室就能稳定养活一个小公司。

### 企业科研/药企

主要在药企与医学院，从事新药研发或实验，最重要是熟悉标准化流程，熟悉质量控制与质量保证。如果你能事先去搞一个六西格玛的黑带认证，那么你的工资会直接提升一个档次，也有可能被当成未来的管理者培养。新兴生物科技公司也会招收高学历的人做包含研发在内的各类工作。在公司做研发，团队成员的知识背景一般差异很大，以产品为导向来进行研究。如果你期望一个相对高的收入、相对宽松的研究环境与几乎为零的经费压力，那么这类行业值得尝试。企业科研的风险在于当外界经济条件非常差的时候有可能整个研发部门都被裁掉。

### 医药交流

这类职业有一定专业要求，需要生命科学或医学药学高学历背景。医药交流主要包括把科研进展带给医生的医学联络官（medical science liaison）
或帮助药厂把新药与疗法传播给客户（medical communication），收取佣金或抽成，要有强大的信息收集处理能力。这个行业是连接药厂、临床大夫与公众的中介，医学联络官薪资不比医生差但需要的技能更侧重交流能力，后面可能成长为医学顾问。

### 咨询

提供解决问题的方案，典型服务业，得有很强的甲方乙方感。咨询行业是少数只看学历不问研究方向的行业，想从事这个行业，必须要有名校学历撑门面，几大咨询公司的学历要求都非常高。此外，咨询公司招人很多也是走校友途径的，他们需要维护一个精英形象。想进这类公司，要有实习经历、要做模拟案例、要会画饼。不过，很多公司请咨询公司并不一定是他们遇到了无法解决的问题，而是他们需要一个光鲜亮丽的第三方经过层层研究用各种花哨新颖的概念名词给出一个他们内部不太好推进的改革方案。你要真是怀着解决实际问题的心态去做项目，那说明你还不了解甲方这个拥有五颜六色的黑心的现代社会物种。

### 金融

工作压力大但收入高，资金流全流程了解，需要洞悉名利场潜规则，容易过度职业化迷失自己。金融行业分为买方与卖方，刚入行一般都是卖方的银行、投行或券商，其主要任务就是将别人的资产包装后卖给买方赚取中介费或佣金，有的则是撰写行业报告或做咨询；买方则是手里有公募或私募来的大笔资金去寻找好的投资标的，赚的是管理费或收益提成。金融行业买方比卖方地位高的同时买方需要的团队也比卖方小，毕竟买或不买是决策，不需要太多人决策。大多数金融行业的人都想从卖方变买方，有科研背景算是一种买方加分。

### 数据科学家

分析数据，更多时候是洗数据与设计数据处理自动化流程，不需要自己写算法但一定要洞悉实际问题的背景知识。这里要说明的是数据科学家跟计算机科学家不一样，喜欢招不限专业博士的是数据科学家，计算机行业招聘几乎一定是限制专业的，所以你要是想做码农，一定要转行拿那边的学位，否则即使进入计算机行业你的博士经历也没有太大用。

数据科学家要同时具备专业知识、统计学知识与计算机编程能力，更多的时候要会传达需求给更专业的人士。数据科学家在不同行业做的事差异挺大的，有的侧重可视化、有的侧重数据库、有的侧重模型等，其实很多数据科学家的职位都有前身，换个名字有时候是为了适应时代需要。博士毕业做数据科学家是需要一些自学能力与相关项目经验的，这些恰好也是很多博士项目培养需要的能力，但并不是说所有拿到学位的博士都适合去做数据科学家，至少你的研究经历得涉及统计跟编程才能靠点谱。

### 创业

适合经济背景、技术独占性还有人脉三者兼备的人去做，不要妄想用一个强势因素去覆盖另外的弱势因素，要找靠谱的合伙人。现在创业有成绩的人并不是突发奇想蹦出来的，这些人大多在校园里就开始参加各类创业大赛累积人脉与技术资源，产品原型与中试可能都做过了。如果你博士毕业仅具备技术实力而没有创业经验，那么前面的坑实在太多。不过，高校一般会有一些专门的机构来辅导学生创业，有些甚至会帮助融资或用学校经费融资换股份。如果你打算创业，一定要充分利用学校给的试错资源，一旦走向社会，即便创业者有心当赌徒搏一把遇到的也大都是不同段位的骗子，能无风险骗到钱或技术他们绝对不赌。
