# 附录二：全栈科学家自测题 {- #scitest}

- 定性定量分子量100-100万的物质需要用到哪些仪器？优缺点是什么

- 多重比较与多重检验的区别与联系是什么？

- 傅立叶变换在光谱分析与质谱分析中的应用场景有哪些？

- 简述21世纪学术圈出现的“可重复性危机”主要指什么？

- ssh远程登录启用图形界面需要加什么参数？

- 野外采样的就餐原则是什么？

- 如何快速将牛腩煮烂？这个方法与提取亚细胞结构的内在联系是什么

- 伪码写一下梯度下降算法

- 简述文献管理的原则与你的方案

- 审稿意见该怎么写？

- 观察实验与控制实验的模型选择有什么区别与联系？

- 两组样品同时测定了100个指标，简述可视化与统计分析两组样品差异与共性的思路

- 冷干法不适于测定生物样品的哪类指标？

- t检验、方差分析、线性模型的共性是什么？

- 超净台日常使用的注意事项及与通风橱的区别

- 15分钟学术报告需要多少张幻灯片？

- 简述引用文献的不规范行为有哪些？

- 给你的研究写一份新闻稿

- 实验室如何进行项目管理

- 什么是编译？为什么有些软件需要编译？

- 三间分布在调查类研究中的常用统计方法有哪些？

- 组学数据的功效分析怎么做？谈下思路

- 完全萃取与不完全萃取的定量原理有什么区别？

- 简述二代测序的原理

- NCBI的常用数据库有哪些？能查到什么信息？

- 石墨、石墨烯、石墨炔、碳纳米管的区别联系

- 从头计算、DFT及分子动力学模拟常用来解释什么问题？

- 主成分分析与偏最小二乘回归的区别与联系

- 用正则表达式提取日期

- 分析化学的灵敏度与统计学的灵敏度概念有何异同？

- agent based model 可以用来做什么？

- 请列出3D打印实验仪器所需要的硬件与软件平台

- 统计模型与仿真模型的区别与联系

- 生物学实验数据log转化的物理学基础是什么？

- 细胞培养防污染需要哪些措施？

- 与非门与异或门是什么？电路标记画一下

- 简述下样品命名的原则

- 随机数如何重现？

- 有限元分析的应用场景有哪些？

- 课题组需要一个网站来发布信息，请简述搭建过程及前端设计

- 实验用品供应商如何联系与筛选？

- 利用网络开放数据可以做什么样的研究，请举例

- 如何鉴定采样得到的植物种属？

- 实验室数据安全需要注意些什么？

- 实验室人员流动时交接程序有哪些？

- 实验室垃圾分类该怎么做？

- 简单说下你对团队协作软件的看法

- 学术伦理主要涉及哪些方面？

- 野外采样期间突发事件如何处理？例如生病、交通延误、地方黑恶势力等

- 如何甄别实验室数据造假？

- 技术重复与生物重复的区别是什么？

- 电镜照片计算平均粒径的方法是什么？

- 探索性数据分析的常见方法有哪些？应用场景是什么？

- 正交试验结果如何解释？

- 自制层析柱有哪些指示物可以用来标示洗脱进度？

- 不同材质手套的使用场景

- 反应釜的温控手段有哪些？

- 常用样品脱水材料或手段有哪些？

- 如何从论文图片中提取数据？

- 如何鉴定培养基污染菌种？

- 如何计算数据处理所需内存？

- 并行计算在CPU与GPU平台上有哪些流行的框架？

- 哪类问题可以进行集群计算？

- 贝叶斯统计的可信区间与置信区间有什么区别？

- 相关不代表因果，那么能代表什么？有哪些其他解释？

- 时间序列最大的特点是什么？

- 常用物质数据库有哪些？

- 谱图比对匹配的算法原理是什么？

- 动态规划算法用来解决什么问题？

- EM算法用来解决什么问题？

- 直接质谱分析与表面增强拉曼光谱各自优缺点是什么？

- 解释下内标法定量

- 无监督聚类有哪些方法？

- 用决策树算法配合重采样技术估计变量重要性如何实现？

- 线性混合模型用来解决什么问题？

- 模型验证方法有哪些？解释下ROC
