# 附录三：科研日常词典 {- #dict}

## 研究生版 {-}

- 研究生：本科生用来缓解找不到工作尴尬的高虚荣底薪工作，导师的廉价劳动力，20世纪中后期中国社会对本科生前景预计的21世纪版
- 博后：博士生用来缓解找不到工作尴尬的高虚荣底薪工作，导师的廉价高产劳动力，北京落户捷径
- 本研：本科来实验室加素质发展分或套瓷推研或拿留学推荐信的进步正能量免费劳动力，外表天真可爱背景完全神秘的NPC，研究生获取外界流行趋势的主要途径
- 师兄：猥琐全能型NPC，口头禅多为“给你挂个二作”，部分具有强社会人属性，部分则从大学阶段就与社会脱节，格子衬衫蓝球鞋迷
- 师姐：已婚的为大姐大型NPC，已育后口头禅多为“我家XX”，XX为孩子小名，未婚的则多徘徊在实验与父母逼婚压力之间，轻度忧郁症晚期患者，匿名出没于晋江起点看言情小说
- 师弟：师姐最常使唤的劳动力，单身优质的属濒危物种，单身普通的则属前者的NPC，格子衬衫蓝球迷
- 师妹：最常使唤师兄的非劳动力，大城市单身的不属于但自认属于的濒危物种，匿名出没于晋江起点写言情小说
- 隔壁组：论文发表在传说中期刊上国奖赏金猎人，与之对话会掉膝盖的NPC
- 聚餐：AA制联谊活动，内因多为撺掇某对师兄弟姐妹，低成功率保障了活动的长期有效
- 学术：研究生过往人生某阶段的终身奋斗目标，后伴随各种打击化作硬币、赞或转发输出给了up主、大v或朋友圈，个别会祸害下一代
- 组会：管饭的廉价劳动力福利，研究生突然主动读文献的原因，师兄会早起的日子
- 学术会议：廉价劳动力平均一年一次的公费旅游/找工作福利，前提是拿到口头报告
- 报告：博后/博士/教职近距离套瓷会，照片多为领导人风格的买家秀，投影/电脑/提问中至少有一个环节会出问题
- csc：流行于海外教授圈的知名廉价劳动力输出与基本生活保障基金
- 校友会：毕业有成的师兄师姐就业内推与装腔组织，毕业无成的师兄师姐收不到或假装收不到通知的组织
- 校友群：毕业后有闲没钱的师兄师姐集赞拉票组织，毕业后无闲没钱的师兄师姐点赞投票组织
- 院/系/实验室年会：课题组长炫富哭穷大赛
- 宿舍：虽然有书有桌有花有独卫，但唯一用到的只有床跟晾衣绳
- 研究生会：存在于楼下大厅海报中的虚拟NPC组织，多运行一个阅读量为泊松分布的院系研会公众号
- 工会：职工运动会组织者，但多调用研究生来获取奖品，研究生运动套装报销组织
- 校医院：在你病怏怏时咨询你过往用药种类与剂量的地方
- 器材：库房里什么都有但就是没有你想要的东西
- 行政：课题组间地下红娘组织，导师佚事集散地
- 财务：视研究生为亲爱的孙子/孙女的非血缘NPC，经常为了先发票后付款与先付款后发票而跟同行赌气，研究生的财会税法启蒙运动支部
- 联合培养：中科院体系广为流行的缓解教育部卡名额的解决方案
- 清真餐厅：最后的物美价廉食堂
- 外卖：会出现在烤串、小龙虾与糖醋里脊之间犹豫半天最终选了当日特价套餐状况的就餐选择
- 番茄工作法：知道、用过、不错、闲置系列产品
- 待办事项：知道、用过、不错、外卖小票背面替代系列产品
- 终身学习：知道、没用过、不错、想用时都收开收智商税了系列产品
- 印象笔记：知道、买过、不错、其实付费功能完全用不到系列产品
- 手帐：知道、买过买不起、不错、单面打印论文背面替代系列产品
- 份子钱：不读研朋友不定期发放的无息融资手段，单身研究生（多数本金无望）节假日旅游目的地邀请函，与知识付费和健身卡并称三大研究生致贫致困原因
- 室友：除了呼噜声都不知其存在的人，桌上灰尘可作画，但其实两人两年都用不了100块的电
- 节假日：研究生自认为可以阅读1元拍下的kindle大部头电子书与某新建文件夹里大量文献但实际只会在参加婚礼与补实验两种状态徘徊的日子，三天常被计划三周都完不成的任务，而且更多时候第一天其实是完全睡过去的
- 周末：虚拟节假日
- 一作：毕业终极目标
- 通讯：经费负责人
- 二作：跟其他作没区别也没用的致谢名单
- 最后一个作者：投稿吉祥物
- 前言：别人做的毫无意义工作的汇总与自己做的开天辟地工作的介绍
- 方法：英文语序转换训练大全
- 结果：阳性结果汇总
- 讨论：别人做的毫无意义工作为什么毫无意义与自己做的开天辟地工作为什么开天辟地
- 结论：开天辟地的另一种摘要式描述方法
- 致谢：导师纠结排序的快结题基金列表
- 查重：某神秘软件，网上可买到服务
- 外审：彩票促销手段
- 毕业论文致谢：实验室过往成员名单，答辩时导师唯一逐字阅读篇章
- 答辩：导师低调装腔的重要场合，研究生镀金完工仪式
- 拨穗：照片之所以丑是因为不是自己拍的
- 审稿：被动读文献的触发条件
- 审稿人：匿名掩盖下的不懂装懂者，完美主义者出没地，他引的广告机会
- 院系所主页：奖学金申请表下载站
- 实验室网站：重点实验室评审时才更新的网站或年轻课题组长默默更新的网站
- BBS：沦为内网后基本消失的研究生吐槽园地
- 知乎：BBS没落后研究生吐槽园地，研究生装腔社会人指南
- 果壳：中科系研究生吐槽但没落园地
- 豆瓣：丧系研究生吐槽园地，此处可自嘲却万不可群嘲，否则后果不堪设想
- B站：研究生不能暴露ID的网站
- 得到：研究生智商税主流收取机构
- 淘宝：师姐妹只看不买系列网站
- 京东：师兄弟只看买不起系列网站
- 支付宝：余额稳定在3-4位数但总被当成6-7位数的研究生理财工具
- 银行流水：研究生15年炒股被套日志
- 加密钱包流水：研究生2017年炒币被套日志
- 科学网：用户平均年龄比果壳知乎高约10岁的有教职学者吐槽园地
- 百度：前言拯救者
- 小木虫：文献下载利器
- MOOC：下定决心开始学新东西但平均出勤不超过三节的在线技校培训网站
- 幻化残生：主流实验学科，科研民工主产区，上述网站研究生的学科来源
- 知识分子：研究生都订阅但只在朋友圈看转发的公众号
- ipv6：研究生娱乐圈与个别研究生学术圈
- 美剧：研究生等待实验结果阶段开着论文实际在看的拖延症病因
- 英剧：其实只为看卷福但要区别于并高于美剧的研究生等待实验结果阶段开着论文实际在看的拖延症病因
- 日剧：看过但不讨论的研究生等待实验结果阶段开着论文实际在看的拖延症病因
- 韩剧：看过但坚决不承认的研究生等待实验结果阶段开着论文实际在看的拖延症病因
- 网剧：为了跟朋友聊天不得不看的等待实验结果阶段开着论文实际在看的拖延症病因
- 泰剧：只看过介绍视频就嘲讽的等待实验结果阶段开着论文实际在看的拖延症病因
- TBBT：无论看不看都说看过的美剧，一般掌握些术语梗且强调其不如英剧《IT狂人》，虽然也没看过
- 星际迷航：根本看不下去但还是要通过百科等途径了解后说看过的伪geek特征梗
- 冰与火之歌：一定要跟着骂马丁但搞不清楚跟《权力的游戏》区别的大尺度美剧的小说，以看过原著为荣
- 西部世界：HBO出品的另一大尺度谈资
- 唐顿庄园：理想英伦生活的装腔指南
- 海贼王：预计啥时完结啥时毕业的动漫
- 银魂：研究生同病相怜的卢瑟指南
- 微信：实验室管理工具，90前自认为的主流交流工具
- QQ：90后或95后研究生私下交流工具
- 朋友圈：论文装腔大赛主会场
- endnote：只在写论文时用但最后还是手工排的文献管理工具
- origin7.0: 网上可下载到的稳定破解版绘图软件
- pdf阅读器：特指adobe acrobat pro而非adobe reader但一定要装破解版的pdf阅读器
- qq邮箱：研究生网上犯事被人肉时的关键线索
- 树莓派：伪geek特征属性，除在线教程外并不知道如何使用
- 彩票：研究生眼中与按期毕业/论文直接接收概率相当所以每到毕业季会买一注来碰碰手气的梦
- 《公务员教材》：研究生代代相传最后全新状态卖了废纸的阶段理想
- 《GRE红宝书》：研究生出国必买不看系列，深夜助眠读物
- 《百年孤独》：这本书的孤独就在于买的人从来不陪伴，研究生深夜助眠读物
- 《麦田里的守望者》：这本书的守望就在于买的人从来不回来，研究生深夜助眠读物
- 《三体》：多数研究生眼中科幻的全部
- 《明朝那些事儿》：多数研究生眼中历史逻辑的全部
- 《解忧杂货店》：读不下去跑去看电影系列
- 《追风筝的人》：读不下去跑去看电影系列
- 《小王子》：不知道为何这么贵系列
- 东野圭吾：日本作家，跟村上春树分不清楚
- 村上春树：日本作家，跟东野圭吾分不清楚
- 清北：两所互相瞧不起但更瞧不起其他国内高校的在排行榜上世界知名的中国高校，知乎上一半用户能攀上关系
- 华东五校：所谓外导除清北外也知道的五所国内高校
- c9: 西交大、哈工大学生网络自我介绍专用
- 985: 除c9外985高校学生网络自我介绍专用
- 211: 除985高校外211高校学生网络自我介绍专用
- 双一流：只有两所高校学生会用的签名档
- 国科大：两所背景深厚高校的共用简称
- 中科院：自诩比肩清北但就业时研究生常因不属于985高校毕业而被刷掉的学位授予机构
- 教育部：各种排名想办法挤兑中科院的学位授予单位
- 科技部：有经费但教科研单位申请较少的单位
- 基金委：不管钱多钱少都有人来申的单位
- 师资博后：多附带口头2年后转讲师或副高的学术过渡期或转行期职位
- 讲师：院系高压全能型群体，职位通常需要行政、教学、科研、打杂等技能
- 青椒：学术圈无职称低收入的焦虑梦想家群体，通常具有博士学历，身份多为师资博后、讲师或助研
- 副高：绝大多数青椒的退休或养老职称
- 教授：多有半年到一年国家支持的海外访学经历且顺带让孩子学英语的副高的退休或养老职称
- 导师：多为非师范院校出身，对教育学一无所知但要表现出无所不知的校园形象，研究生的老板，实验室级创业公司合伙人，社交活动家，比乞丐学历高（疑似）的职业募捐者
- 帽子：各类人才项目总称
- 青千：海归博士博后的归国意愿保障体系高校版
- 百人：海归博士博后的归国意愿保障体系中科院版
- 百篇优博：优秀高校土鳖博士认证，中科院系统已退出评选
- 优青：杰青的低配版
- 长江学者、杰青、大千人：院士的低配版，学科间利益协调系统，各学科子学科代言人队伍，学科级会议分会场keynote报告人
- XX学者：除长江学者外一般为省级或地方人才引进项目负责人，长江学者、杰青、大千人预备队或评审人员
- 青基、面上、重大：基金委的职称评定指南，申请人基本对应中级、副高及正高职称，拿到后有希望晋级
- 两院院士：学科间利益协调系统，学科级会议大会报告报告人与吉祥物
- 基金委子学科主任：身份等同两院院士的金主
- 副校长：研究方向跟会议研究主题完全无关的致辞人
- 领导：省/市级分管科教的二把手，无研究方向的会议致辞人
- 纸：学科内高水平期刊论文
- 水：学科内非高水平期刊论文
- 中科院分区：期刊划分标准，在除中科院体系外的科教单位中流行
- 核心期刊：本科生科研成果汇编
- SCI：研究生科研成果汇编
- h-指数：自引狂魔不会用，青年学者用不了，中年学者纳入讲座海报介绍的指数，一般至少两位数才会报
- 影响因子：一般用分来形容，描述期刊的面子，分越高面子越大，但要避免PO，SR等雷区
- CNS：评职称利器，帽子敲门砖，根据学科情况子刊也算
- 开放获取：高收费期刊的另一个名字

## 留学生版 {-}

- 三件套：Costco会员卡、宜家家具与二手车或二十手车
- 西服：留学生求职必备，平时吃灰
- Business casual：最灵活的着装要求，但留学生几乎都会overdressed，除非你在东部
- 国货：质优价廉代表
- 品牌差：国内定位中高端，国外定位平价的品牌，传递的SES（社会经济地位）信号自然也不一样
- 双肩包：多为带学校校徽的联名款背包，留学生通勤必备
- 微信厨房：以微信群为阵地的中餐预订平台，价格公道不上税，常见一队华人排队在一辆私家车后备箱取餐
- 闷烧杯：留学生必买不用系列
- 落地灯：留学生必买，因为住处一般没有灯，另外记得同时买灯泡
- 慢炖锅：留学生买前想的都是美食，买后只处于吃灰与熬粥两种状态
- 平底锅：留学生必买懵圈系列，对炒菜极其不友好，还是去亚超买圆底炒锅熬宽油过瘾
- 老干妈、王致和、王守义：拯救留学生厨艺的三位东方先贤
- 烤箱：留学生不会用系列，燃气的传统烤炉需要火柴或点火器引燃，玩火系列
- 咖啡机：办公室必备，融入美式八卦文化的关键，但至少要分清阿拉比卡种（Arabica）和罗伯氏特种（Robusta），否则还是喝茶或饮水处按水好些
- 微波炉：留学生午餐必备
- 可乐鸡翅：留学生必会菜谱，包纳了两种超市里差不多最便宜的食材
- 冷冻蔬菜：用来制造冰箱比较满幻象的伪健康食品
- 西红柿炒鸡蛋：留学生必会菜谱，西红柿一般用番茄酱代替
- 左宗棠鸡：美式中餐的典范，lunch special
- 橙子鸡：trader joe‘s 必买冷餐
- seminar：free lunch special
- Tariarki：日式中餐的典范，其实是过量的酱油
- Gyro：中东卷饼
- Bagel：空心扁馒头
- pizza：摊大了的馅饼，没有皮
- 三明治：方形多层馅饼，对角切开卖
- 培根：五花肉替代品，省的腌了
- 热狗：便宜的异形肉夹馍
- 韦斯特醋：国内叫辣酱油，烧烤肉类用
- spaghetti：面条，需要煮时间长点
- pita: 中东卷饼
- taco: 墨西哥卷饼
- 鲭鱼罐头：日本留学生经常买
- Tandoori：与印度朋友聚餐首选鸡肉，否则你想象不到他们的禁忌会是啥
- Pho：跟兰州拉面一样流行的越南米粉
- pops/soda/coke：碳酸饮料代称，有地域特色
- double double：加拿大TH首选糖奶味咖啡
- subway：其实你只要说all of them就好了而不必纠结调味料单词是什么，防尴尬点餐：daily special-white bread-full length-no cheese-heat, pls-onion/tomato/pickle/cabbage/cucumber-barbecue sauce-that's it-thanks
- 电影：手里备几张 AMC black ticket 还是很有必要的
- casino：自助比较便宜，但别买筹码，否则就贵了
- 寿司店：老板多是中国人，卖的多是紫菜包饭
- 米其林：留学生17年之前的旅游必备体验项目
- 城市：一般泛指硅谷与纽约曼哈顿
- 谷：特指硅谷，特特指硅谷码农
- 街：特指花街，特特指华尔街金融民工
- 下谷上街：理工科留学生毕业首选，研究生肄业转行目的地
- 农村：绝大多数不在硅谷与曼哈顿学校的生存环境
- CSSA：留学生租房、二手交易、接送机信息集散地，多有公众号
- 统舱：大开间，具备厨房独立卫生间，多见于城市
- house：别墅，一般主卧自带卫生间，次卧常需要共享卫生间，所有住客共享大厅与厨房
- 公寓：租金比house贵，有的自带卫生间，共享大厅厨房，没有主卧次卧之分
- 半土库：一面有出口或落地窗的地下室，多自带卫生间，性价比之王
- 土库：租金最便宜的地下室，有些地方不合法
- 积分卡：留学生买菜购物累计里程享受折扣必备
- 健身卡：留学生钱包里有但几乎不用或几乎天天用的卡
- 保险卡：最应该替代钱包健身卡所占卡槽的卡
- prime会员：学生身份免费半年外带半价，但也会有几人共用一个号的情况
- plaza：农村住宅区之间的商区，一般会有一个大超市、一个小超市、一家银行、一家披萨或subway或DQ、一家中餐馆、一家美式餐馆、一家牙医诊所与一家美甲店，路对面会有一到两个带便利店的加油站
- 1元店：留学生文具耗材补充基地，可以感受家乡的气息
- photoID：带照片、生日与签名的政府签发身份证明，护照、驾照比较常见
- 住址：用来判断税款的信息，但可以租邮箱
- 驾照：留学生为了不用天天带护照与身份证明而办的，农村留学生生活必需品
- 灰狗：没车留学生进城工具
- carpool：留学生进城或接送机工具，总能找到华人在做
- 加油返利信用卡：养车留学生必备
- discovery免年费信用卡：留学生拿到ssn首选信用卡
- 唐人街：留学生理发、买熟食与寄快递的地方
- xx大学留学生微信群：通常人数是满的，但常发言的只有几个表演欲强的人
- Asian fit：留学生配眼镜专属型号，不然会达成眼镜贴脸成就
- mitbbs：中年有身份有孩子华人吹牛灌水发泄之处，中年无身份华人求审稿机会平台
- dealmoon：留学生购物指南，返利养活了一个产业
- Reddit：类似贴吧的存在
- cashback：收银处储蓄卡取现金服务，但现在更多人理解为信用卡的返现
- reference number：报案或投诉一定要记住的号码
- 小费：留学生手机计算器的主要应用场景
- 税表：意外收入来源
- 邮件列表：留学生想移到垃圾邮件又不想错过重要信息的学校内部信息源
- 月末聚会：系里或学校学生会组织的庆祝月华虚度的饮料畅饮尬聊会
- 大秘：特指系里秘书，绝对不能惹又绝对可依赖系列
- Dean：退休前faculty的养老服务类职位
- 副教授：系里八卦来源，要么云淡风轻，要么忙忙碌碌评教授
- AP：小心翼翼的常任轨新兵，每日遛娃申基金重写论文，重度焦虑患者
- 博后：千老居多，虽然大多数期望拿教职，但最后大都转SRA培养下一代去了
- opt：美帝三年暂住证
- 宠物：留学生独居心灵寄托，但多数房东不让养，富人区里多为妇女社交工具
- 97移民：特指说粤语的香港移民，回归前跑到了其他英联邦国家
- 柳丝绿卡：因为某次事件的移民身份大赦，但抢占了后来100年的华人移民名额
- 留学炒房团：一出国就买房，上学时同时做房东，房租还按揭，毕业了卖掉，因为是学区房，差价大概相当于留学学费的玩法，投资需谨慎
- 新移民：新世纪以来通过留学后拿到身份的留学生，与前面修铁路、偷渡的早期移民及改革开放后八九十年代之交移民的高华聊不到一起，喜欢用微信
- 计划生育移民：多数称孩子被强制打掉获取身份的同胞，少数是真的
- 民运移民：多数称被政府迫害获取身份的同胞，少数是真的
- 大法：多数称被政府迫害获取身份的同胞，多数自认为是真的，领着国内退休金，喜欢强行传教并运营神韵晚会
- 华人教会：不少同胞的灵魂归宿，然，不乏龌龊事
- 陪读妈妈：这个词本身就是个故事
- 政评人：活跃在油管上以取悦海外华人与营造优越感为生的自媒体
- 月子中心：制造事实上两国国籍同胞的组织
- 孔院：一般跟语言学校混在一起的组织，办公室常年冷清
- ABC：美国华裔二代移民
- CBC：加拿大华裔二代移民
- Amigo：拉美友人统称
- Bro：非洲友人统称
- 大妈团：背着单反来国外扫货的退休大妈，特别亲切，但不受待见
- 宣讲会：留学生归国鬼门关，多是高校副校长带队
- 流浪汉：uptown大街上强词夺理要钱的人
- 青千：千老海归们眼中类似五险一金的归国保障计划
- bless you：可用来估计留学时长的打喷嚏后问候语，不说的一半都是短期访问
- 简历：cv跟resume是有区别的，前者是完整记录，后者是针对职位的优化版，通常一页纸，多数压力过载的HR喜欢且只喜欢看后者。

## 创业隐喻 {-}

- 投资人：政府或企业
- 公司：项目或课题
- 董事长：课题组长（PI）
- 经理：小老板或子课题负责人
- 项目经理：博士生／硕士生／本科生
- 员工：无
- idea／论文：产品
- 质检员：审稿人
- 产品上市：论文发表
- 产品发布平台：学术期刊
- 产品未通过内部质检：论文拒稿
- 产品有销量：论文被引用
- 产品成为爆款：论文被大量引用
- 产品被媒体推荐：论文被编辑或综述点评
- 产品滞销：论文无引用
- 产品原料配料表：论文数据共享
- 产品生产流程：数据处理
- 产品被模仿：论文被重复验证
- 产品补丁：论文修正
- 产品更新换代：论文跟进发表
- 产品推介会：学术会议
- 产品退市：论文撤稿
- 公司融资：申请基金
- 新三板／创业板：申请青基
- A股：申请面上
- 路演：项目申请书
- 估值：学术影响力
- 竞争公司：研究方向
